### ISSUE TITLE
Unable to specify custom package name

### ISSUE THREAD

**Issue by jbub** [facebookincubator/ent#113]
I have this `generate.go` file in my `./internal/ent` directory:

```
package ent

//go:generate go run github.com/facebookincubator/ent/cmd/entc generate --target=store ./schema
```
When i run `go generate ./internal/ent` from the root of my project, it generates ent files under `./internal/ent/store`, but inside those files, for example `client.go`, the package is `package ent`, but it should be `store`.

**Comment by jbub** [comment]
The use case is, i want to separate generated code from schema definition files.

**Comment by a8m** [comment]
Closing since there's already an issue for solving this problem #61.
I have a fix for this. I'll try to land it in the upcoming days.

**Comment by jbub** [comment]
Oh sorry havent noticed that issue, thanks!
