### ISSUE TITLE
override id column

### ISSUE THREAD

**Issue by marwan-at-work** [facebookincubator/ent#127]
Is there a way to redeclare the id column as a custom string type? 

If I put the following in my schema: 

`field.String("id").Unique()`

The generated code ends up broken because it creates two declarations of "id", but furthermore it ignores the fact that it's a string, and declares it as an integer instead. 

This might be related to the UUID discussions, but it would be great if we can define our own custom primary keys as strings that we provide at runtime.

**Comment by alexsn** [comment]
Currently the "id" field is implied so there's no way to override the underlying storage key. The above setting should give a better error message where a reserved field name is used.

**Comment by alexsn** [comment]
Are you looking to rename the "id" column name, provide your own PKs or both?

**Comment by a8m** [comment]
This is part of our roadmap and it should be addressed in the upcoming week (or 2).
I linked this issue to the roadmap item.

**Comment by marwan-at-work** [comment]
@alexsn im not looking to rename "id". I'm looking to keep it "id" but change its type from integer to string, and also be able to provide my own value when i create a row. 

Thanks :v:

**Comment by BitPhinix** [comment]
Seems to work with the lastest branch, but there isn't a uuid type available. Is there any way to use a Postgres UUID primary key with ent?

**Comment by a8m** [comment]
Hey @BitPhinix, this feature is still in development. 
I'll update the issue (and the roadmap) once we finish the implementation.

**Comment by aca** [comment]
@a8m Feature Proposal 
I think it is related to this, so I write it here.
Can we customize struct tag for field "id" ?

I'm currently using type generated by ent, and I want to make json reponse with no ID field.
Which is achievable by Sensitive() for other fields.
But It seems it is impossible to make edit struct tag for ID field.

```
type Project struct {
    ent.Project
    ID `json:"-"`
}
```
I thought I could solve this by doing something like this. But didn't worked well.

**Comment by a8m** [comment]
Hey @aca, did you try to override the struct tag? See - https://entgo.io/docs/schema-fields/#struct-tags

**Comment by aca** [comment]
@a8m I meant ID field which is generated by entc not by defining ent.Field
```
// Fields of the Namespace.
func (Namespace) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").Unique().Match(regexp.MustCompile("[a-z0-9]+(?:[._-][a-z0-9]+)*")).NotEmpty(),
		field.Int64("id").StructTag("-").Unique(),
	}
}
```
Defining "id" field doesn't seems to work. Really sorry If I misunderstood.

**Comment by a8m** [comment]
There's no option to override the ID's struct-tag except using custom template (which is too complex in this case imo). 

This definitely should be addressed. I'll update the issue once we get to it.

**Comment by gukz** [comment]
Hey, dear @a8m , I am rewriting a project with go , I enjoy using ent, but this project has a table with a `user_id` primary key. Can ent allow specify any field as the primary key?

**Comment by a8m** [comment]
> Hey, dear @a8m , I am rewriting a project with go , I enjoy using ent, but this project has a table with a user_id primary key. Can ent allow specify any field as the primary key?

I run the codegen with this option in the schema and it worked for me.
```go
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id").
			StorageKey("user_id"),
		// more fields..
	}
}
```
The database in MySQL was created as follows:
![image](https://user-images.githubusercontent.com/7413593/72155349-9cc0bf80-33bb-11ea-865f-c0f4a190f52a.png)


You are welcome to try it. 

Like I mentioned above, once we get to this task, we'll handle all these cases.
Thanks!

**Comment by marwan-at-work** [comment]
I know the issue is still being worked on, but just as an update: 
Defining an ID as a string no longer creates a build error, but it now generates a runtime error when running a migration. 

Given the following `field.String("id").Unique()`

The following create table happens: 

`sql/schema: create table "specs": Error 1071: Specified key was too long; max key length is 767 bytes`

The interesting part, is that if I change the schema to say: `field.String("id").Unique().MaxLen(25)`

Then the same error happens. I noticed that the `schema.go` file doesn't populate the "id" Size the same way it would do for other fields. 

If I manually change `schema.go` inside the migrate directory to include `Size: 25` then the migration successfully works.

**Comment by a8m** [comment]
Hey @marwan-at-work and thanks for reporting these issues. Regarding your comments:

> Given the following field.String("id").Unique()
>
> The following error shows up from the create table operation:
>
> sql/schema: create table "specs": Error 1071: Specified key was too long; max key length is 767 bytes

I'm aware about this and it should be addressed. I'm pretty sure this is the last thing left for closing this issue. 

> @a8m another issue I discovered (just in case you missed it), is that where.go tries to convert an ID string to an integer while ignoring the error, which results in always bringing back the first row.

Where did you encounter this code? in your generated code or in this repository? If you don't run codegen with `--idtype string`, the logic shouldn't be there. 

This (legacy) option was added to allow using the same generate `ent` package for both AWS Neptune (`gremlin`) and SQL dialects. Neptune uses UUID strings for its IDs, and MySQL is configured with numeric types for its PKs (in our deployment). Therefore, the type in the code must be string, and we convert it to int before/after the data were loaded. 

I don't see any reason for using this option, except our exceptional case that was used for migrating from Neptune to MySQL. I'll suggest to not use it because we plan to drop it soon.

**Comment by marwan-at-work** [comment]
@a8m 

> Where did you encounter this code?

I'm using the latest commit of `entc` and I was not aware of the `--idtype` flag at all. So I was just using `entc generate ./ent/schema` 

I created a reproduction repository here: https://github.com/marwan-at-work/entrepro

You can see that my schema has the following ID definition https://github.com/marwan-at-work/entrepro/blob/master/ent/schema/spec.go#L14:L22

But then then the code that was generated from `entc generate ./ent/schema` gave these results: https://github.com/marwan-at-work/entrepro/blob/master/ent/spec/where.go#L21:L26

If that can just be removed from the template, I'm happy to contribute a fix, here's what I did locally and it seemed to work: https://github.com/marwan-at-work/ent/commit/e3b004b07b1ee6074d9363b7e49cbaaf4a7228d8#diff-a01877e4cc82393fb3d3f48188992b02

Thanks!

**Comment by a8m** [comment]
Thanks for helping debugging this @marwan-at-work.
That looks like a bug (I need to deep dive into it), but it can't be solved with just removing this part from the template (for the reason I've commented above). 

I'll update once it's fixed.

**Comment by a8m** [comment]
Thanks for helping debugging this @marwan-at-work.
That looks like a bug (I need to deep dive into it), but it can't be solved with just removing this part from the template (for the reason I've commented above). 

Can you please run the codegen as describe [here](https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent), or just use:
```
go run github.com/facebookincubator/ent/cmd/entc generate ./ent/...
```
Just to make sure we're running the same version (as in go.mod). 

---

I'll update once it's fixed.

**Comment by a8m** [comment]
@marwan-at-work - I've added a fix for this, and checked it on your repo using this version: `github.com/facebookincubator/ent@9733051cc361`.

Please check it and update me if there's any issue with this.

**Comment by marwan-at-work** [comment]
@a8m just tried it with that commit and it looks great!!

**Comment by a8m** [comment]
All comments that were raised in this issue addressed (hopefully), although there are some docs changes that need to be done.

Please give it a try and update us if there's any issue with this. Closing.

**Comment by jiamo** [comment]
If we have multi schema in same dic. I only want one schema replace `id`. Can we put `idtype` in schema file instead using option `--idtype`?

**Comment by nvhai245** [comment]
I think it would be better if we support some options to define a different primary key for schema, for example:
`field.String("uid").PrimaryKey()`

**Comment by a8m** [comment]
You can. See the second option here: https://entgo.io/docs/schema-fields#id-field
