### ISSUE TITLE
Byte type of field fails to migrate on PG,  on pq: column "image" contains null values

### ISSUE THREAD

**Issue by pavelz** [facebookincubator/ent#142]
Adding to table definition: 

```
		    field.Bytes("image").
			   Nillable().
			   Default([]byte("hi")),

```
Won't migrate the table, whether there is Nillable() or not.

2019/11/06 12:32:24 failed creating schema resources: sql/schema: alter table "users": pq: column "image" contains null values

**Comment by a8m** [comment]
Can you replace the `Nillable` option with `Optional` in this schema? (I wonder how does it work for you with `Nillable` and not `Optional`; because `Nillable` requires `Optional`). 

Please let me know if it does/not work for you.
Thanks

**Comment by pavelz** [comment]
thank you for your reply, yes .Optional() works and allows migration with NULLable column but migration does not set DEFAULT for some reason - as with String type. Suppose update to migrations is in order.

**Comment by a8m** [comment]
> but migration does not set DEFAULT for some reason - as with String type

We intentionally do not apply the default value on the database for blob type, because it doesn't support by all dialects (MySQL for example).
