### ISSUE TITLE
Feature Request: Support UpdateDefault for other field types

### ISSUE THREAD

**Issue by greyg00s** [facebookincubator/ent#148]
https://github.com/facebookincubator/ent/blob/4aa550a68f4055830819d553a529bfd3c6e016a4/schema/field/numeric.go#L10

I was looking to switch my db fields from time fields to Unix time be to time zone agnostic.

**Comment by a8m** [comment]
Thanks for opening this issue.

Unlike `field.Time`, the default value for numeric types is just a static value.
Regarding your issue (time as unix format), I wonder what's the right thing to do:
- Add support for different format for time fields
- `UpdateDefault` should get a function 
- Or just leave it as it is today

I'll leave it open to see what others have to say about this.

**Comment by greyg00s** [comment]
Think should be a function like time field. This way would be able to pass time.Now().Unix as a function, or some other user defined function. At which the user can pass a generic function, but might like func() int, but it might do some additional calculations before returning a value.

**Comment by a8m** [comment]
> Think should be a function like time field. 

Currently, the `Default` value for numeric field is a Go numeric value and not a function. Therefore, if you want to define a default value (on create) for an int field that will be used as a unix time you won't be able to use `time.Now().Unix`.

Also, I like the idea that `Default` and `UpdateDefault` have the same type. 

It looks like an issue/proposal for a specific problem (that sounds reasonable), and I think maybe the solution is just to add a format option to the time field.

**Comment by mrasong** [comment]
Maybe add a `Timestamp` type is a better way.

**Comment by a8m** [comment]
Hey,
This issue is sitting here for a long time, and since we don't have plans to change the API and lose the type-safety of the schema, I suggest that you'll use [hooks](https://entgo.io/docs/hooks/) for tackling this problem.

You can define a hook on a specific type as follows: 
```go
// A hook that sets the default value for "name" field of the Card entity.
hook := func(next ent.Mutator) ent.Mutator {
	return hook.CardFunc(func(ctx context.Context, m *ent.CardMutation) (ent.Value, error) {
		if !m.Op().Is(ent.OpCreate) {
			return next.Mutate(ctx, m)
		}
		if _, ok := m.Name(); !ok {
			m.SetName("unknown")
		}
		return next.Mutate(ctx, m)
	})
}
```

Or, you can share one hook with multiple types:
```go
// A hook that sets the default value for "name" field of an entity.
hook := func(next ent.Mutator) ent.Mutator {
	return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
		namer, ok := m.(interface {
			Name() (string, bool)
			SetName(string)
		})
		if !ok || !m.Op().Is(ent.OpCreate) {
			// Skip if the mutation does not have a method for
			// setting the name, or it's not a "Create" operation.
			return next.Mutate(ctx, m)
		}
		if _, ok := namer.Name(); !ok {
			namer.SetName("unknown")
		}
		return next.Mutate(ctx, m)
	})
}
```

Please let us know if you have any problems with it. Closing
