### ISSUE TITLE
Indexes with only Edges

### ISSUE THREAD

**Issue by htdvisser** [facebookincubator/ent#150]
Given the following in `ent/schema/`:

```go
func (PublicKey) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("user", User.Type).
			Ref("public_keys").
			Unique(),
	}
}

func (PublicKey) Indexes() []ent.Index {
	return []ent.Index{
		index.Edges("user"),
	}
}
```

`entc generate` refuses to create an index on the `user_id` column of `public_keys`, with the error:

```
entc/gen: invalid index for schema "PublicKey": missing fields
```

Perhaps this only makes sense for SQL databases, but it should be possible to configure an index on `user_id`, right?

It looks like making this possible only require a small change in

https://github.com/facebookincubator/ent/blob/4aa550a68f4055830819d553a529bfd3c6e016a4/entc/gen/type.go#L378-L382

I can submit a pull request, but importing/reviewing that would probably take more time than it would take the maintainers to push a commit, or pulling it into their work on https://github.com/facebookincubator/ent/issues/91.

**Comment by a8m** [comment]
Sounds reasonable.

I can quickly add this tomorrow, but let me know if you want to contribute this change.

Thanks.
