### ISSUE TITLE
Add Indexes/Edges/Hooks to Mixin

### ISSUE THREAD

**Issue by htdvisser** [facebookincubator/ent#151]
Currently the `Mixin` interface only contains fields:

https://github.com/facebookincubator/ent/blob/4aa550a68f4055830819d553a529bfd3c6e016a4/ent.go#L132-L136

I think it would be nice to support indexes for the fields that are in the mixin, so that I could define something like:

```go
type ColorMixin struct{}

func (ColorMixin) Fields() []ent.Field {
	return []ent.Field{
		field.String("color"),
	}
}

func (ColorMixin) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("color"),
	}
}
```

**Comment by htdvisser** [comment]
I'd also be happy with something like a `.Indexed()` on the `field.xxxBuilder`s (similar to `.Unique()`) to create a single-column index for that field. 

This approach would also work for single-edge indexes, and my example in #150.

**Comment by a8m** [comment]
I like both suggestions.

I’ll comment in more details tomorrow (weekend time). Thanks

**Comment by a8m** [comment]
Adding `Indexes` to `Mixin` sounds good to me. I like the other suggestion too, but I feel like it's adding too much complexity to the codebase just for a syntactic-sugar like API (I'm not saying it's bad, just not sure what I think about this).

**Comment by a8m** [comment]
Done with #431 
Thanks for proposing this.
