### ISSUE TITLE
MySQL with non-nullable foreign key columns

### ISSUE THREAD

**Issue by n3v3rf411** [facebookincubator/ent#167]
I have an existing database schema from which I create schema objects from. The foreign key columns in the existing schema are non-nullable. When I create a new child entity in a O2M relationship, MySQL throws an error like as follows:
```
Error 1364: Field 'user_id' doesn't have a default value
```

In the generated `xxx_create.go` `sqlSave` function, the foreign key columns seem to be set after insertion.

Is there some other way to make this compatible other than setting these foreign columns as nullable? I checked the generated migration script produced by ent and the foreign key columns are indeed nullable.

**Comment by a8m** [comment]
Hey @n3v3rf411,
Thanks for opening this issue.

You are right, `ent` indeed updates the fields first, and only then update the edges.
However, we're working on changing the storage layer to be more dynamic and optimized in cases like this as well. 

> Is there some other way to make this compatible other than setting these foreign columns as nullable?

Currently, I don't have a quick solution for this, but I'll keep you updated if anything will change.

**Comment by n3v3rf411** [comment]
I could do with setting the columns to nullable for now.

Thanks for the great work, btw 😁

**Comment by fr3fou** [comment]
any news?

**Comment by a8m** [comment]
Hey, following my previous comment - 

> You are right, ent indeed updates the fields first, and only then update the edges.

Since v0.1.0, `ent` updates all table columns (including FKs) on `INSERT`.

However, setting the edge to be unique, won't make it non-nullable. 

Closing, and thanks for your collaboration guys!
