### ISSUE TITLE
field.String/field.Text generates int8 type field

### ISSUE THREAD

**Issue by WinPooh32** [facebookincubator/ent#191]
Hello.
I am trying to generate code by example schemas and all string fields are generated as int8. As I know it begins to happen after [this commit](https://github.com/facebookincubator/ent/commit/7be1779ad1343636916463dfe92b57181476f1c1).

`entc describe` [output](https://gist.github.com/WinPooh32/7fdb27ff5847c1d774d83fd3d151bf1e) for examples/start.

**Comment by a8m** [comment]
Can you upload please your schema?

**Comment by a8m** [comment]
Another question please - are you working with go modules? 

I assume your `ent` version and `entc` are not identical. 
Please try to follow this [guide](https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent), and let me know if it does fix your problem.

**Comment by WinPooh32** [comment]
> I assume your ent version and entc are not identical.

Thank you, I just forgot to update entc:
`go get -u github.com/facebookincubator/ent/cmd/entc`
