### ISSUE TITLE
Cannot run command entc init <name> outside go path

### ISSUE THREAD

**Issue by AN-Cesc** [facebookincubator/ent#194]
hi team, I'm a beginner for golang. I have got a problem when using it to generate schema.

- first step: I create a new folder, change directory to it and run command go mod init <project-name>
- second step: I install entc framework using command go get github.com/facebookincubator/ent/cmd/entc
- third step: I run command entc init User, but I have got a message -bash: entc: command not found

I already check inside gopath exists entc execute the file. Please help me resolve the issue. thanks

**Comment by a8m** [comment]
Can you replace please “entc init” with “go run github.com/facebookincubator/ent/cmd/entc init <arguments>”? 

This [example](facebookincubator/ent/blob/master/examples/start/ent/generate.go#L7) in the examples package contains a complete command.

**Comment by AN-Cesc** [comment]
I can be done by using "go run github.com/facebookincubator/ent/cmd/entc init ...". thanks for the support. but I can't access example hyperlink you provide

**Comment by a8m** [comment]
Here's the link - https://github.com/facebookincubator/ent/blob/master/examples/start/ent/generate.go#L7

I'm closing issue, but feel free to open if you still have troubles.
Thanks

**Comment by AN-Cesc** [comment]
thank you, I did pass through the issue
