### ISSUE TITLE
migrations with sqlite3

### ISSUE THREAD

**Issue by erikh** [facebookincubator/ent#200]
I have roughly the schema below, and on the second pass of Schema.Create, it gives this stack trace. I notice on the documentation near the trace it says sqlite3 can't be used in "append-only" mode because it's "just for testing". Is that the current state of things? If so I can just change my database targets.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x957333]

goroutine 1 [running]:
github.com/facebookincubator/ent/dialect/sql/schema.(*Migrate).changeSet(0xc00011f740, 0x0, 0x10b6c40, 0xc8f660, 0xc00015a860, 0xbb0ea2)
        /usergo/pkg/mod/github.com/facebookincubator/ent@v0.0.0-20191125181359-be307dab3c93/dialect/sql/schema/migrate.go:241 +0x63
github.com/facebookincubator/ent/dialect/sql/schema.(*Migrate).create(0xc00011f740, 0xc8f460, 0xc0000a0000, 0xc8f660, 0xc00015a860, 0x10b0920, 0x3, 0x3, 0xbd9320, 0xc00011f740)
        /usergo/pkg/mod/github.com/facebookincubator/ent@v0.0.0-20191125181359-be307dab3c93/dialect/sql/schema/migrate.go:121 +0x1b6
github.com/facebookincubator/ent/dialect/sql/schema.(*Migrate).Create(0xc00011f740, 0xc8f460, 0xc0000a0000, 0x10b0920, 0x3, 0x3, 0x0, 0x0)
        /usergo/pkg/mod/github.com/facebookincubator/ent@v0.0.0-20191125181359-be307dab3c93/dialect/sql/schema/migrate.go:104 +0x11f
github.com/tinyci/services/service/usersvc/ent/migrate.(*Schema).Create(0xc0000ab6c0, 0xc8f460, 0xc0000a0000, 0x0, 0x0, 0x0, 0x0, 0xc0000d0d80)
        /usergo/src/github.com/tinyci/services/service/usersvc/ent/migrate/migrate.go:48 +0x12a
```

Schema:

```go
// User holds the schema definition for the User entity.
type User struct {
  ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
  return []ent.Field{
    field.String("username").Immutable().Unique(),
    field.String("password"),
    field.Time("created_at").Immutable().Default(time.Now),
    field.Time("updated_at").Default(time.Now),
  }
}

// Edges of the User.
func (User) Edges() []ent.Edge {
  return []ent.Edge{
    edge.To("capabilities", Capability.Type),
    edge.To("tokens", AuthToken.Type),
  }
}

// Capability holds the schema definition for the Capabilities entity.
type Capability struct {
  ent.Schema
}

// Fields of the Capabilities.
func (Capability) Fields() []ent.Field {
  return []ent.Field{
    field.String("capability").Immutable().Unique(),
  }
}

// Edges of the Capabilities.
func (Capability) Edges() []ent.Edge {
  return []ent.Edge{
    edge.To("users", User.Type).Unique(),
  }
}


// AuthToken holds the schema definition for the AuthToken entity.
type AuthToken struct {
  ent.Schema
}

// Fields of the AuthToken.
func (AuthToken) Fields() []ent.Field {
  return []ent.Field{
    field.String("service").Immutable(),
    field.String("token").Sensitive(),
    field.Time("created_at").Immutable().Default(time.Now),
    field.Time("expires_at").Immutable().Nillable().Optional(),
  }
}

// Edges of the AuthToken.
func (AuthToken) Edges() []ent.Edge {
  return []ent.Edge{
    edge.To("user", User.Type).Required().Unique(),
  }
}
```

**Comment by a8m** [comment]
Hey @erikh, thanks for reporting this issue.

As it [mentioned](https://entgo.io/docs/dialects/#sqlite) in the docs, `ent` does not support incremental updates for schema, since (in our case) it's used only for testing. 

I don't think it's a problem to add support for it (although, some things are not clean, like adding FK for existing table), it just wasn't in our priority. 

Are you using `sqlite` outside testing?

**Comment by erikh** [comment]
Thanks, I guess I missed this, sorry for the noise.

I was just planning on using it for simplistic scenarios where I'd use ent; the system itself is designed to run in compact and large environments which makes the multi-driver support a great dovetail with what I'm doing (a CI system). Basically I want a "CI in a box" for small, testing/evaluation situations and a more scalable, distributed system that would more normally leverage postgres in my case; mysql seems like it could be used too which makes me happy but is less relevant.

For now, I can just give the "box" as a docker-compose file that contains a postgres deploy as well as the CI deploy. This works for my needs for now.

That said, the flexibility of sqlite3 would be nice, and I'd love to assist with these changes if you're willing to guide me on what needs to be done in your codebase. I am comfortable in golang and with databases.

**Comment by erikh** [comment]
...that was a lot of words to say "basically, I want to use one container instead of N". :)

**Comment by a8m** [comment]
Thanks for the rich comment @erikh :)

> That said, the flexibility of sqlite3 would be nice, and I'd love to assist with these changes if you're willing to guide me on what needs to be done in your codebase.

That can be great. I don't have all details in front of me this moment, but I remember that implementing a real incremental migration for SQLite was a bit PITA (like the FK example above). 

There's no much code to do in the migration, since most of the migration logic is generic and execute dialect specific operations. There are just a few open issues that we need to decide how we tackle them, and the implementation part should be simple. 

I can post here tomorrow the requirements for SQLite and we can continue from there.

**Comment by erikh** [comment]
Sounds great. Thanks!

**Comment by erikh** [comment]
it's a holiday here in the states, so no big deal, but I wanted to remind you that I'm still interested in doing this work for you.:)

**Comment by alexsn** [comment]
@erikh, we'll provide an update tomorrow.

**Comment by a8m** [comment]
> it's a holiday here in the states, so no big deal, but I wanted to remind you that I'm still interested in doing this work for you.:)

Great, and sorry for the delayed response.
I think we can start by discussing about how we handle the case of adding FKs to existing tables.
I know that one popular approach is to re-create the table and copy the data, but I wonder if it's really feasible for production environments. Any thoughts?

**Comment by erikh** [comment]
It looks like sqlite3 supports transactional DDL. From what I'm reading it looks like certain operations are allowed and others aren't... CREATE INDEX is a great example of something people are having trouble making transactional in sqlite3. Similar to postgres.

I'll look more later this week.

**Comment by erikh** [comment]
To the FK issue, did you see something specific from sqlite3 that I'm not aware of, or is this a general "we can't find the key in the db, abort abort and don't break anyone" issue?

**Comment by a8m** [comment]
> To the FK issue, did you see something specific from sqlite3 that I'm not aware of, or is this a general "we can't find the key in the db, abort abort and don't break anyone" issue?

The problem I had that time was that I couldn't add the `ADD CONSTRAINT` with `ALTER TABLE`. 
But, from going over the documentation again, I saw that it can be done as follows:
```sql
ALTER table t1 ADD COLUMN c1 int REFERENCES t2(c2) ON DELETE SET NULL;
```

Wonderful!

**Comment by erikh** [comment]
it looks like the SQL builder is going to need to support sqlite3 `pragma` statements before I move further. do you have a preferred way to do this? it seems very "select"-centric at the moment at a glance.

**Comment by a8m** [comment]
The current SQLite schema code already [executes `pragma`s](https://github.com/facebookincubator/ent/blob/master/dialect/sql/schema/sqlite.go#L23). However, it doesn't have any special API for this in the builder, just uses `Exec(...)`. Does it help somehow? 

I think the best way to start is [here](https://github.com/facebookincubator/ent/blob/master/dialect/sql/schema/sqlite.go#L151). Basically, load the table from SQLite schema to Go struct (in order to generate the [`changeSet`](https://github.com/facebookincubator/ent/blob/master/dialect/sql/schema/migrate.go#L221-L234) that need to be applied on the database). 

Let me know if you need any help with that.

**Comment by erikh** [comment]
Yeah I was working with the equivalent postgres code already. I just didn't see this bit about the pragma use. This helps a ton; should have something in a day or two.

**Comment by erikh** [comment]
I started #221 (linking these two) to discuss changes to the outstanding patch.

**Comment by tv42** [comment]
Here's another vote for "didn't notice this in the docs" and "would be great to use sqlite properly for small projects". Thank you!

**Comment by tv42** [comment]
For anyone else passing through here, a quick way to kludge your way forward is to force sqlite migrations to be manual, and skip `client.Schema.Create` if any tables already exist. For that, you need to use `ent.NewClient` not `ent.Open` to have access to the underlying sql DB.

```
import entsql "github.com/facebookincubator/ent/dialect/sql"
```
```
	drv, err := entsql.Open("sqlite3", "file:test.sqlite?_loc=auto&cache=shared&_fk=1")
	if err != nil {
		return err
	}
	defer drv.Close()
	db := ent.NewClient(ent.Driver(drv))
	defer db.Close()

	const haveAnyTable = `SELECT COUNT(*) FROM "sqlite_master"`
	row := drv.DB().QueryRow(haveAnyTable)
	var numTables int
	if err := row.Scan(&numTables); err != nil {
		return err
	}
	if numTables == 0 {
		if err := db.Schema.Create(ctx); err != nil {
			log.Fatalf("failed creating schema resources: %v", err)
		}
	}
```

**Comment by erikh** [comment]
Hey; sorry the patch is so late. I've just been really busy. I'd encourage you to watch #221 for new developments, however, it's a long thread.

**Comment by a8m** [comment]
The "append-only" migration was added with #428. More advanced migration features (like dropping resources) will be added in the future - I'll open a separate issue for it.
