### ISSUE TITLE
Q: recommended way to add aditional constraint?

### ISSUE THREAD

**Issue by aca** [facebookincubator/ent#212]
Hi, I'm trying to add additional constraint rule. But It seems impossible in ent.
Would you recommend a way to add it after Schema.Create() ?
Should I just not use it at all? And initalize schema in other way?

I need something like this.
user / project / role
role has constraint unique (user, project)

**Comment by a8m** [comment]
> I need something like this.
user / project / role
role has constraint unique (user, project)

You mean, you want to define a unique index on these 3 fields? If so, please give a look on the [indexes](https://entgo.io/docs/schema-indexes/) page in the website and let me know if it does solve you problem or not.

**Comment by a8m** [comment]
Closing this for now.
Please open if you still have troubles.

**Comment by aca** [comment]
@a8m Sorry, missed that one. Didn't know I can pass multiple arguments to index.Edges().

For someone who read this..

```
func (RoleBinding) Indexes() []ent.Index {
	return []ent.Index{
		index.Edges("user", "namespace").Unique(),
	}
}
```
