### ISSUE TITLE
Clever use of edges causes code gen failure

### ISSUE THREAD

**Issue by erikh** [facebookincubator/ent#214]
```go
package schema

import (
        "github.com/facebookincubator/ent"
        "github.com/facebookincubator/ent/schema/edge"
        "github.com/facebookincubator/ent/schema/field"
)

// Ref holds the schema definition for the Ref entity.
type Ref struct {
        ent.Schema
}

// Fields of the Ref.
func (Ref) Fields() []ent.Field {
        return nil
}

// Edges of the Ref.
func (Ref) Edges() []ent.Edge {
        return []ent.Edge{
                edge.To("names", RefName.Type),
        }
}

// RefName holds the schema definition for the RefName entity.
type RefName struct {
        ent.Schema
}

// Fields of the RefName.
func (RefName) Fields() []ent.Field {
        return []ent.Field{
                field.String("name"),
                field.Bool("tag"),
        }
}

// Edges of the RefName.
func (RefName) Edges() []ent.Edge {
        return []ent.Edge{
                edge.From("ref", Ref.Type).Ref("names"),
        }
}
```

`entc generate` passes this with flying colors, but generates code which will not compile:

```
erikh@tinyci src/test% go install -v ./...                                                                                 [5:54]
test/migrate
# test/migrate
migrate/schema.go:36:2: RefNamesColumns redeclared in this block
        previous declaration at migrate/schema.go:23:2
migrate/schema.go:41:2: RefNamesTable redeclared in this block
        previous declaration at migrate/schema.go:29:2
```

Renaming the `From` edge ref to `ref_names` seems to resolve the issue.

**Comment by a8m** [comment]
Thanks for reporting this issue.

I’ll give it a look.

**Comment by a8m** [comment]
After I went over this example, I think that in cases like this, using `ent.Config` is preferred. For example: 
```go
func (RefName) Config() ent.Config {
	return ent.Config{
		Table: "entref_names", // Or any other name.
	}
}
```
I'm also a bit biased here, because I don't want to make internal things too clever.
Closing it, but feel to open if you still have troubles.

**Comment by erikh** [comment]
That's fine, I don't take any issue with that, but `entc generate` should detect it before generation if possible. Is that a hard problem with the way the code is organized? I don't have a lot of weight in this argument; I just thought I would suggest that.

**Comment by a8m** [comment]
> should detect it before generation if possible. 

I think this should be addressed, and it's pretty easy to solve. 

---

I just want to explain my previous comment for later readers -  _"I don't want to make internal things too clever"_.

Currently, `ent` generates table names as plural for types as follows:
```
User => users
UserType => user_types
Equipment => equipment 
``` 
But, since M2M edges require a join table, `ent` needs to generate for them a table as well.
The table name convention for edges is basically: `<type>_<edge>`. Now, in case of conflict, what name `ent` should use? (I don't really know, because I want a readable and meaningful name). 

By not solving the problem, I'm kinda giving the end-users to choose for themselves.
