### ISSUE TITLE
Question: how to select and scan a user and all his pets(O2M) into a struct?

### ISSUE THREAD

**Issue by kidlj** [facebookincubator/ent#220]
Suppose that `User` and `Pet` has a O2M relation, and the following is the result type I want to scan into

```
type UserPets struct {
  Name string `json:"name",
  Age int `json:"age",
  Pets []Pet `json:"pets",
}
```

How to select and scan results into such a struct variable ? 

Thanks.

**Comment by a8m** [comment]
Hey @kidlj, Eager-loading is currently under development and should be done soon. 
See #91 for more details. 

You're welcome to give feedback on the design in the linked issue. 
Thanks
