### ISSUE TITLE
Question: Field Migrations

### ISSUE THREAD

**Issue by chris-rock** [facebookincubator/ent#233]
I am trying to implement migrations properly with ent. Let's assume we have an entity user. We already  collected data in that table:

```
// User schema.
type User struct {
    ent.Schema
}

// Fields of the user.
func (User) Fields() []ent.Field {
    return []ent.Field{
        field.Int("age"),
        field.String("name"),
        field.String("username").
            Unique(),
    }
}
```
Now, I want to and a new field:
```
field.Time("create_time").Default(time.Now()),
```

The migration will fail with `column \"create_time\" contains null values"`. I'd like to understand what your recommended way is? I see at least two options:

1. Combine ent migration with custom logic:
- allow nilable values when I add new fields
- migrate data (or create the required ones)
- change field to not-nilable
2. manage sql migrations outside of ent

**Comment by a8m** [comment]
Unlike strings, numbers and booleans, timestamp fields can't have default values on the database using the `DEFAULT` clause.

When you define a time field as follows:
```go
field.Time("create_time").
    Default(time.Now)
```
The default function (`time.Now`) will be invoke on `ent` side. 

Now, if you want to add a new field that can't have a backfill in the database, you can define it as optional as follows (which is nullable in the database):
 ```go
field.Time("create_time").
    Optional()
```
If you want to distinguish between nullable and zero values in your code, add the `Nillable()` option to the field definition. 

---

I agree that this is not optimal for migration, but it's on our roadmap and we plan to tackle this before v1. I assume that one of the options will be to allow custom code to be executed as part of the migration process.

**Comment by a8m** [comment]
Thanks for raising up this issue.
I'm closing, but feel free to continue the discussion or to open if you still have troubles.

**Comment by chris-rock** [comment]
Thank you for the clarification @a8m

**Comment by Gbps** [comment]
To fix this myself with auto migration, I had to use the following definition:

```go
field.Time("timeField").Default(func() time.Time { return time.UnixMilli(0) }).Optional().Nillable()
```
and manually edit `./migrate/schema.go` to edit the field definition to:
```go
{Name: "timeField", Type: field.TypeTime, Nullable: true},
``` 
so it includes the `Nullable` field.

I don't know why this process is so involved to add a nullable time field, but this seems to have worked.
