### ISSUE TITLE
SQL contraints are not removed when field.Unique() is removed

### ISSUE THREAD

**Issue by chris-rock** [facebookincubator/ent#235]
If you define a field with a unique constraint it will properly set to the data-model
```
return []ent.Field{
   field.String("name").Unique(),
}
```

Now, remove the constraint:
```
return []ent.Field{
   field.String("name"),
}
```
That change will not be propagated to the database. You can still see the constraint defined:
```
CONSTRAINT users_name_key UNIQUE (name)
```
I observed this behavior with postgres. Not tested with Mysql.

**Comment by a8m** [comment]
Did you use the DropIndex option?
https://entgo.io/docs/migrate/#drop-resources

**Comment by chris-rock** [comment]
I have not tested it with DropIndex, since I have not defined the field as an index.

**Comment by a8m** [comment]
You can also use the “offline mode” to verify changes before dropping resources.
https://entgo.io/docs/migrate/#offline-mode

**Comment by a8m** [comment]
> I have not tested it with DropIndex, since I have not defined the field as an index.

Postgres (or MySQL) automatically creates a unique index when a unique constraint is added to a column, and ent migration works by default on “append-only” mode. So, if you want to drop resources, you need to ask this explicitly.

**Comment by chris-rock** [comment]
I think I narrowed down the issue. Let's assume you create a new entity like:

```
type TestUser struct {
	ent.Schema
}

func (TestUser) Fields() []ent.Field {
	return []ent.Field{
		field.Int("age"),
		field.String("name"),
		field.String("nickname"),
	}
}

func (TestUser) Edges() []ent.Edge {
	return []ent.Edge{}
}

func (TestUser) Index() []ent.Index {
	return []ent.Index{
		index.Fields("age", "name").
			Unique(),
	}
}
```

This will generate the following correct SQL statement:
```
CREATE TABLE IF NOT EXISTS "test_users"("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "age" bigint NOT NULL, "name" varchar NOT NULL, "nickname" varchar NOT NULL, PRIMARY KEY("id"));
```

If we are going to add a `Unique()` statement:
```
func (TestUser) Fields() []ent.Field {
	return []ent.Field{
		field.Int("age"),
		field.String("name"),
		field.String("nickname").Unique(),
	}
}
```
a new index will be created via:
```
CREATE UNIQUE INDEX "test_users_nickname" ON "test_users"("nickname");
```
once we remove the uniqueness, a correct drop is generated:
```
DROP INDEX "test_users_nickname";
```

The issue occurs, when you generate the entity with the uniqueness for the first time directly:

```
type TestUser struct {
	ent.Schema
}

func (TestUser) Fields() []ent.Field {
	return []ent.Field{
		field.Int("age"),
		field.String("name"),
		field.String("nickname").Unique(),
	}
}

func (TestUser) Edges() []ent.Edge {
	return []ent.Edge{}
}

func (TestUser) Index() []ent.Index {
	return []ent.Index{
		index.Fields("age", "name").
			Unique(),
	}
}
```

Then ent will generate the following sql statement with an contraint instead of an index:
```
CREATE TABLE IF NOT EXISTS "test_users"("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "age" bigint NOT NULL, "name" varchar NOT NULL, "nickname" varchar UNIQUE NOT NULL, PRIMARY KEY("id"));
```

This leads to the following result in postgres:

```
CREATE TABLE nexus.test_users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    age bigint NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    nickname character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT test_users_pkey PRIMARY KEY (id),
    CONSTRAINT test_users_nickname_key UNIQUE (nickname)
)
```

Then the drop index statement will not work, because a constraint had created for the table:

```
DROP INDEX "test_users_nickname_key";
```
will result in
```
ERROR:  cannot drop index test_users_nickname_key because constraint test_users_nickname_key on table test_users requires it
HINT:  You can drop constraint test_users_nickname_key on table nexus.test_users instead.
```

**Comment by a8m** [comment]
Thanks for this comment @chris-rock, I'll give it a look tomorrow morning. 

What Postgres version are you using?

**Comment by chris-rock** [comment]
I used the postgres dialect to generate the SQL statements via ent's offline mode. I tested everything with the postgres:12-alpine container

**Comment by a8m** [comment]
Thanks for the report and the support @chris-rock
Please feel free to open if you still have troubles with the migration.

**Comment by chris-rock** [comment]
Thank you for your PR @a8m This fixes the issue that constraints are not properly deleted 🥇 

I think there is still the question if ent should create an index for constraints:

changing

```go
field.String("name").Unique(),
```

to

```go
field.String("name")
```

will generate

```sql
ALTER TABLE users DROP CONSTRAINT "users_name_key";
```

once, we re-add the uniqueness, it will create an index instead of a constraint:

```go
field.String("name").Unique(),
```
```sql
CREATE UNIQUE INDEX "users_mrn" ON "users"("mrn");
```

What do you think @a8m?

**Comment by a8m** [comment]
Hey @chris-rock,
Do you have any pros/cons about the 2 strategies? I like the current approach because the code looks the same for all dialects (but I don't mind to change it if it's incorrect).   

I know that Postgres documentation suggests to use constraint because index is an "implementation details":

>  The use of indexes to enforce unique constraints could be considered an implementation detail that should not be accessed directly.

Also, I need to check the difference in table locking (if there's one) between the 2 commands. 

Thanks and sorry for my delayed response.
