### ISSUE TITLE
bug fix:Can't get field comment

### ISSUE THREAD

**Issue by hantmac** [facebookincubator/ent#246]
<img width="836" alt="截屏2019-12-1610 34 53" src="https://user-images.githubusercontent.com/7600925/70875147-e9e58780-1fef-11ea-9114-0555f235b494.png">

If I want to get the comment of a `Edge` I failed because the `Comment` field not defined in the `Descriptor`. I fix it in https://github.com/facebookincubator/ent/pull/244.

I'm not sure if we need such an operation,please review it.Thanks!

**Comment by hantmac** [comment]
And I found the same problem in `Field` package, fixd in https://github.com/facebookincubator/ent/pull/247

**Comment by a8m** [comment]
Hey, thanks for raising up this issue. 

It's not a bug.  The `Comment` exists for historical reasons, and it's not used by `entc` (`ent` codegen) - no need to export it in the `Descriptor`.

**Comment by hantmac** [comment]
> Hey, thanks for raising up this issue.
> 
> It's not a bug. The `Comment` exists for historical reasons, and it's not used by `entc` (`ent` codegen) - no need to export it in the `Descriptor`.

Got it! Thanks!
