### ISSUE TITLE
Problem: db groups generated by `entc generate` can't open

### ISSUE THREAD

**Issue by hantmac** [facebookincubator/ent#248]
Hey, I am trying to use `ent` according to `getting start` https://entgo.io/docs/getting-started/, But after using `entc generate Car Group`, and create some data in db using next code:
```
func CreateGraph(ctx context.Context, client *ent.Client) error {
	// first, create the users.
	a8m, err := client.User.
		Create().
		SetAge(30).
		SetName("Ariel").
		Save(ctx)
	if err != nil {
		return err
	}
	neta, err := client.User.
		Create().
		SetAge(28).
		SetName("Neta").
		Save(ctx)
	if err != nil {
		return err
	}
	// then, create the cars, and attach them to the users in the creation.
	_, err = client.Car.
		Create().
		SetModel("Tesla").
		SetRegisteredAt(time.Now()). // ignore the time in the graph.
		SetOwner(a8m).               // attach this graph to Ariel.
		Save(ctx)
	if err != nil {
		return err
	}
	_, err = client.Car.
		Create().
		SetModel("Mazda").
		SetRegisteredAt(time.Now()). // ignore the time in the graph.
		SetOwner(a8m).               // attach this graph to Ariel.
		Save(ctx)
	if err != nil {
		return err
	}
	_, err = client.Car.
		Create().
		SetModel("Ford").
		SetRegisteredAt(time.Now()). // ignore the time in the graph.
		SetOwner(neta).              // attach this graph to Neta.
		Save(ctx)
	if err != nil {
		return err
	}
	// create the groups, and add their users in the creation.
	_, err = client.Group.
		Create().
		SetName("GitLab").
		AddUsers(neta, a8m).
		Save(ctx)
	if err != nil {
		return err
	}
	_, err = client.Group.
		Create().
		SetName("GitHub").
		AddUsers(a8m).
		Save(ctx)
	if err != nil {
		return err
	}
	log.Println(client.Group.Query().All(ctx))
	log.Println("The graph was created successfully")
	return nil
}
```

Then I open the mysql terminal and exec `desc groups`, got errors:
<img width="1464" alt="截屏2019-12-1617 55 49" src="https://user-images.githubusercontent.com/7600925/70897332-59c63300-202d-11ea-8bfd-46ea14c8b519.png">
But the other tables like users, cars, are all ok:
<img width="1324" alt="截屏2019-12-1617 57 50" src="https://user-images.githubusercontent.com/7600925/70897438-9a25b100-202d-11ea-8326-fab2d5207578.png">

Any information need I provide?

**Comment by a8m** [comment]
`groups` is a reserved keyword in MySQL8. You should quote it as an identifier as follows: 
```sql
select * from `groups`;
```

**Comment by a8m** [comment]
Feel free to open if you still have troubles.

**Comment by hantmac** [comment]
> Feel free to open if you still have troubles.



> `groups` is a reserved keyword in MySQL8. You should quote it as an identifier as follows:
> 
> ```sql
> select * from `groups`;
> ```

Thans for your reply! But my mysql version is 5.7, anyway, `select * from `groups;` solved.

**Comment by hantmac** [comment]
> Feel free to open if you still have troubles.

Thanks!
