### ISSUE TITLE
How to add `Log` when create `ent.NewClient`

### ISSUE THREAD

**Issue by vctqs1** [facebookincubator/ent#250]
I would like to create `ent.NewClient(ent.Driver(drv))` and add log here?

But how to use `Log(fn func(...interface{}))` here. Please give me example. Many thanks

https://sourcegraph.com/github.com/facebookincubator/ent/-/blob/entc/integration/json/ent/config.go#L23:2&tab=references

**Comment by a8m** [comment]
What are you trying to do? Passing a custom log function, or log queries?

**Comment by vctqs1** [comment]
> What are you trying to do? Pass a custom log function, or log queries?

`custom log`

**Comment by a8m** [comment]
Here's an example that replaces the default `Log` function with `log.Println`.
```go

import (
     "log"
     
     "<pkg-path>/ent"
)

func main() {
	client, err := ent.Open("<dialect>", "<conn-string>", ent.Log(log.Println))
	if err != nil {
		log.Fatalf("failed to open client: %v", err)
	}
	defer client.Close()
        // ...
}
```
I hope it helps.
Closing, but feel free to open if you still have questions.

Thanks!
