### ISSUE TITLE
run `go test example_test.go ` in `/ent/examples/entcpkg` failed

### ISSUE THREAD

**Issue by hantmac** [facebookincubator/ent#261]
I run `go test example_test.go ` in `/ent/examples/entcpkg` But got the error as flowings:

<img width="991" alt="截屏2019-12-2516 58 59" src="https://user-images.githubusercontent.com/7600925/71440415-0001ef00-2738-11ea-8368-25bee5e1226f.png">

The I want to found `spec.ScanTypes`, but I did not, does the template has bug?

**Comment by a8m** [comment]
Thanks for reporting this issue! 
I pushed a change yesterday and forgot to regenerate the examples assets (I still need to check why it passed the CI)

I submitted a patch for this.

**Comment by hantmac** [comment]
> regenerate the examples assets

Emm.I wanna to know how to regenerate the examples assets?

**Comment by a8m** [comment]
```console
go generate ./...
```

**Comment by hantmac** [comment]
> ```
> go generate ./...
> ```

Thanks!
