### ISSUE TITLE
Inheritance and Raw query support

### ISSUE THREAD

**Issue by ansarizafar** [facebookincubator/ent#269]
Is there any plan to add table Inheritance https://www.postgresql.org/docs/10/tutorial-inheritance.html feature?

ent should also allow raw query, a type-safe escape hatch for highly-optimized queries or queries ent don't yet support.

**Comment by a8m** [comment]
Hey @ansarizafar 

> Is there any plan to add table Inheritance https://www.postgresql.org/docs/10/tutorial-inheritance.html feature?

We currently focus on our [roadmap](#46), and don't have plan to support this.

> ent should also allow raw query, a type-safe escape hatch for highly-optimized queries or queries ent don't yet support.

I'm not sure I get this. What stops you from executing custom queries and decode them into `ent` objects?  Note, that it's also possible to add [custom predicates](https://entgo.io/docs/predicates/#custom-predicates) to `ent` queries.

**Comment by ansarizafar** [comment]
> What stops you from executing custom queries and decode them into ent objects?

Is there an example of custom queries with ent available somewhere?

**Comment by a8m** [comment]
Use the [`sql.Exec/Query`](https://golang.org/pkg/database/sql/#example_DB_ExecContext) directly or see the example in #85. 

Closing, since I don't have any action to take here.
Thanks!

**Comment by ansarizafar** [comment]
I understand you are busy working on roadmap for V1 but Inheritance is a nice feature for data modeling. Please consider adding this feature after V1.
Thanks for the amazing project.

**Comment by a8m** [comment]
> Inheritance is a nice feature for data modeling. Please consider adding this feature after V1.

I agree, and we'll definitely consider more features after V1. I just don't want to commit to something that we won't be working on in the upcoming months.

Thanks!

**Comment by ansarizafar** [comment]
There is a related project https://github.com/prisma/prisma2 specifications https://github.com/prisma/specs. Take a look when have time. May be we can borrow some ideas.
