### ISSUE TITLE
pascal panics in some cases during generating files

### ISSUE THREAD

**Issue by danf0rth** [facebookincubator/ent#272]
Hi!

Specifying empty string for the field cause panics. 

__Steps to reproduce__

1. Create schema with empty enum field name:

```
// Fields of the Pet.
func (Pet) Fields() []ent.Field {
	return []ent.Field{
		field.Enum("").Values(
			"A",
			"B",
			"C",
		),
	}
}
```
2. `entc generate ./ent/schema`
3. see it panics

__Reason__

https://github.com/facebookincubator/ent/blob/b54007ef5686f1bcfaff0e8280b718252f49e079/entc/gen/func.go#L108

In any of this cases `pascal` will panic: 

- empty string
- starting from _underscore
- ending with underscore_

Test file:
```
func Test_pascal(t *testing.T) {
	type args struct {
		s string
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{
			name: "empty string",
			args: args{s: ""},
			want: "",
		}, {
			name: "starting from underscore",
			args: args{s: "_example"},
			want: "_Example",
		}, {
			name: "ending with underscore",
			args: args{s: "example_"},
			want: "Example_",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				if err := recover(); err != nil {
					t.Fatalf("recovered: %s", err)
				}
			}()
			if got := pascal(tt.args.s); got != tt.want {
				t.Errorf("pascal() = %v, want %v", got, tt.want)
			}
		})
	}
}

```

__Possible solutions how to fix:__

- return error when using empty field name (best solution for me, because for empty field name is difficult to generate schema, and etc.)
- check w is not empty before passing to `rules.Capitalize` call
- create PR to https://github.com/go-openapi/inflect or fork-and-fix

If the first solution is ok, i can send PR

**Comment by a8m** [comment]
I think the easiest way to handle this, is simply to reject fields without name.
#273 should fix this.

**Comment by a8m** [comment]
> return error when using empty field name (best solution for me, because for empty field name is difficult to generate schema, and etc.)

Oh, I just saw this option. 
I really sorry about this, I saw the bug and just fixed this automatically (while working). 
I hope you'll have more opportunities to contribute code at the future.
Thanks and sorry (again!)
