### ISSUE TITLE
Enum with name of reserved Go keyword breaks codegen

### ISSUE THREAD

**Issue by danf0rth** [facebookincubator/ent#275]
Hi!.

__Steps__

1. `field.Enum("chan").Values("a", "b", "c"),`
2. `entc generate ./ent/schema/`
3. see that codegen uses reserved golang keywords

Solutions, either use name transformed by https://github.com/facebookincubator/ent/blob/b93958ebf41655714d3dc7d3937327bd0ad01036/entc/gen/type.go#L712 or deny using reserved keywords at all. 

I just tried to fork and fix it with `builderField` and it seems works fine.

Thanks!

**Comment by a8m** [comment]
Hey @danf0rth and thanks for reporting this issue.
Is it a really use case? If so, you are welcome to send a PR.

**Comment by a8m** [comment]
Closed with #276
