### ISSUE TITLE
New drivers

### ISSUE THREAD

**Issue by gedw99** [facebookincubator/ent#281]
Are you open to new driver ?

Tidb is one dB I use for global scale. 
Tidb kv store.

What I want to do is try to write a driver for tidb kv so I can use it embedded.

Tidb is just SQL postresql wire format. So pretty straight forward.

**Comment by a8m** [comment]
Hey @gedw99 and thanks for opening this issue.

> Are you open to new driver ?

As I answered about the dgraph support in the [roadmap](#46) issue:

> > Would there be interest in support for Dgraph?
>
> Currently, we want to focus on our roadmap and don't want to commit to something we don't have the capacity for it (because it means maintaining and supporting a storage-driver we're not using nor have experience with).
>
> However, @alexsn and I just discussed this morning on adding a public interface for pluggable storage-drivers. So, if someone is willing to take and maintain this, I'll be happy to help.

Having said that, if TiDB is PostgreSQL compatible, you can already use it today.

**Comment by winwisely99** [comment]
Ok I will try out tidb and report back..
