### ISSUE TITLE
entc/gen: foreign-key name is changed when an inverse-edge is added/dropped

### ISSUE THREAD

**Issue by a8m** [facebookincubator/ent#285]
Title is self explanatory. It's a known issue we found today, and currently working on a backward compatibility fix for it.

Should be addressed soon.

**Comment by kidlj** [comment]
The storage key for edge is kind of confusing.

Taking the o2o-recursive [demo](https://entgo.io/docs/schema-edges/#o2o-same-type) as an example, `node_next` in db table actually means `node_prev`.

```
id	value	node_next
2	2	1
3	3	2
4	4	3
5	5	4
1	1	5
```
