### ISSUE TITLE
Schema creation/migration fails when using MySQL and uint32

### ISSUE THREAD

**Issue by danf0rth** [facebookincubator/ent#287]
Hi!

**Steps to reproduce**:

1. `entc init City`
2. Create uint32 field.
```
func (City) Fields() []ent.Field {
	return []ent.Field{
		field.Uint32("population"),
	}
}
```
3. `entc generate ./ent/schema`
4. Run `client.Schema.Create(ctx)`
5. Run it once again
6. Get error: `sql/schema: changing column type for "population" is invalid (int unsigned != int)`

In database column has type:
```
`population` int(10) unsigned NOT NULL,
```

Not sure why this happens, but this occurs on both MySQL 5.7 and MySQL 8.0 and only with `uint32` (i checked `uint8`, `uint16` and `uint64`, all of them works fine). I guess, parser that check existed schema thinks that column type is `int`, but expected `unsigned int`, but not really sure.

**Comment by a8m** [comment]
Thanks for reporting this @danf0rth. I'll give it a look.

**Comment by danf0rth** [comment]
@a8m latest master commit.
`github.com/facebookincubator/ent v0.0.0-20200113192409-f270e41f6e45`

**Comment by a8m** [comment]
OK. I'm not able to reproduce this. 
I'm suspecting that it's a different problem. Can you please run codegen as mentioned [here](https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent) and update me if it still happens? 

Basically, run `go run github.com/facebookincubator/ent/cmd/entc generate ./ent/schema`

**Comment by danf0rth** [comment]
@a8m still having the issue. 

- tried run `go run github.com/facebookincubator/ent/cmd/entc generate ./schema`
- tried `generate.go` and `go generate ./ent`
- tried to remove `entc` binary
- tried `go mod verify` and `go mod tidy`

Not sure if this related, i am tested with `mysql:latest` and `mysql:5.7` docker images.

**Comment by a8m** [comment]
> OK. I'm not able to reproduce this.

I've typed accidentally `Int32` instead of `Uint32`. I'm able to reproduce it now. 
Sorry and thanks for your patience :)
