### ISSUE TITLE
Feature: Provide a flag to disable example test generation

### ISSUE THREAD

**Issue by erikh** [facebookincubator/ent#297]
These tests are incompatible with the flags I pass to `go test ./...`. A `git clean -fx` with a proper `.gitignore` KOs them but I'd really prefer a flag to `entc generate`.

Really enjoying using ent for a few microservices I've been hacking on, thanks for making it!

**Comment by hantmac** [comment]
> go test ./...

`go test ./...` may be affected by the account of test sqllite,mysql,or psql.

**Comment by erikh** [comment]
It's because i'm using testify and passing `-testify.m` to the package list
in entirety. it's not a user error the tests just don't process that flag
right. Every time I generate the schema I need to remove these tests.

>

**Comment by hantmac** [comment]
> It's because i'm using testify and passing `-testify.m` to the package list in entirety. it's not a user error the tests just don't process that flag right. Every time I generate the schema I need to remove these tests.
> […](#)

I got it, you don't need these tests files every time  generate the schema using `entc generate`.
Yeah It is convenient to provide a flag to disable example tests generation.

**Comment by alexsn** [comment]
Don't see a good enough reason to overload `entc`with extra flags. Just run `ent generate && rm <test_file>` instead.

**Comment by erikh** [comment]
Can I please set something to not generate the examples I don't need at all
for the operation of this system. If it's environment variables; great!
That works too.

I just really don't see the value in making a feature of entc being "here's
some files to delete". That is a very unattractive feature of a code
generator.

**Comment by a8m** [comment]
Agree with @alexsn, it's much simpler to add `rm` to your `go generate ./...` command instead of adding this logic to `ent`. 
I'm actually in favor of deleting this `example_test` file completely from `ent`. It was created before we had a proper documentation ([entgo.io](https://entgo.io)).
