### ISSUE TITLE
Feature request: spatial data types

### ISSUE THREAD

**Issue by briancharous** [facebookincubator/ent#306]
Has there been any consideration of adding support for spatial data types to ent?

Specifically, I'm looking for to create an entity with a field that generates a `POINT` data type in the underlying database, and the ability to query for entities wherein the point lies within some geometry. As far as I can tell there also isn't an "escape hatch" built into the generator in which columns of unsupported types can be created and queried with custom SQL. I'm really excited by this project, and correct me if I'm wrong, but if a table with geospatial types is a requirement, that disqualifies ent today.

If this is something that the community and maintainers would be interested in, I'd be happy to help develop this feature.

**Comment by hantmac** [comment]
Which kind of database will you want to support this feature for ent?

**Comment by a8m** [comment]
Hey @briancharous, and thanks for submitting this issue. 
The need is clear to us, and we definitely should let users to add their dialect-specific types.

There's already an issue for this (#277) and I'll suggest that we move the discussion to there. 

Closing, but feel free to open if you think it's needed.
