### ISSUE TITLE
Eager loading doesn't seem to work for M2M

### ISSUE THREAD

**Issue by ligustah** [facebookincubator/ent#334]
Hello,

I think there's a bug in the generated code for M2M eager loading. I don't have a simple test case to share, but I've done some digging and I think I found the issue:

I have two entities `Person` and `Email` (ignore for a second the fact that this shouldn't be a M2M to begin with 😬). I'm trying to query a specific `Person` with id `124`:
```go
client.Person.Query().WithEmails().Where(person.ID(124)).Only(ctx)
```

That query will return the person, but the `Emails` will not be populated on the `PersonEdges` (the flag for the edge is set on the `loadedTypes however`). Looking at the queries it seems to me like it's picking the wrong column from the second query to use for the third. (I removed the explicit field lists to make it easier to read):
```sql
SELECT DISTINCT * WHERE "persons"."id" = $1 LIMIT $2 -- args=[124 2]
SELECT "person_id", "email_id" FROM "person_emails" WHERE "person_id" IN ($1) -- args=[124]
SELECT DISTINCT * FROM "emails" WHERE "emails"."id" IN ($1, $2) -- args=[124 124]
```

If we check out the generated code, we can see why:
```go
// in person_query.go
Assign: func(out, in interface{}) error {
	eout, ok := out.(*sql.NullInt64)
	if !ok || eout == nil {
		return fmt.Errorf("unexpected id value for edge-out")
	}
	ein, ok := in.(*sql.NullInt64)
	if !ok || ein == nil {
		return fmt.Errorf("unexpected id value for edge-in")
	}
	outValue := int(eout.Int64)
	inValue := int(eout.Int64)        // <---- this should be ein
	node, ok := ids[outValue]
	if !ok {
		return fmt.Errorf("unexpected node id in edges: %v", outValue)
	}
	edgeids = append(edgeids, inValue)
	edges[inValue] = append(edges[inValue], node)
	return nil
},
```

I tried fixing it in the code generator, but I didn't immediately understand what the [template code](https://github.com/facebookincubator/ent/blob/27935a8/entc/gen/template/dialect/sql/query.tmpl#L329) is supposed to do, so I'll leave that to someone else 😬 (my guess would be changing the `"eout"` to `$arg`)

When I changed it in the generated code it started working for me, so I'm going to assume that should fix it.

**Comment by a8m** [comment]
Thanks for reporting this issue @ligustah. 
Can you please paste here your schema definition for `Person` and `Email`?

**Comment by a8m** [comment]
> Can you please paste here your schema definition for Person and Email?

Don't need. I found the issue. 

We missed this, because we run codegen with a different config in integration - I'll try to add a better CI coverage for eager-loading this week.

Thanks for help!

**Comment by ligustah** [comment]
Awesome, that was a quick fix!
Looking good to me, but I'll give it a test run

Thanks
