### ISSUE TITLE
Feature request: adding custom Marshalling and Unmarshalling

### ISSUE THREAD

**Issue by Aterocana** [facebookincubator/ent#340]
My organization was evaluating ent for a little project we have internally.
We are pleased with the framework, but we mainly miss a couple of feature:

1. we'd like to define additional field on the edges (field on relation, for example having entities `Person`, `Dog` and the edge `owner` with the field `time_spent_together`). I haven't open this issue for this since I saw this missing feature is already in current issues.
2. we'd like to Marshal and Unmarshal structs in formats other than json one, which is automatically included in struct's field tags. We'd like, if possible, define the tags in the schemas, or something similar, in order to deal with different format (for example, we use internally jsonapi and toml).

Thank you, great tool so far. Congrats.

**Comment by a8m** [comment]
Hey @Aterocana, and thanks for opening this issue. 

> My organization was evaluating ent for a little project we have internally.

Happy to hear this.

> we'd like to define additional field on the edges (field on relation, for example having entities Person, Dog and the edge owner with the field time_spent_together).

Like you mentioned above, it's part of our roadmap.

> we'd like to Marshal and Unmarshal structs in formats other than json one, 

If I got you right, you want to define custom struct tags on the generated entities? If that's the case, `ent` already supports this. Please check the [struct-tag doc](https://entgo.io/docs/schema-fields/#struct-tags).


Let me know please if we can close this issue.

**Comment by a8m** [comment]
Closing. Please open if it's not working for you.

**Comment by Aterocana** [comment]
It's working: thank you very much
