### ISSUE TITLE
`IsNotFound` is not true when a sqlgraph's updater's target was not found

### ISSUE THREAD

**Issue by joewreschnig** [facebookincubator/ent#341]
The `IsNotFound` check for errors included in the generated code does not work for updates; [`updater`'s `scan` returns a new error which also does not unwrap into anything](https://github.com/facebookincubator/ent/blob/b93958ebf41655714d3dc7d3937327bd0ad01036/dialect/sql/sqlgraph/graph.go#L715). It seems like an update to a not-found node should also qualify as something `IsNotFound` can detect, or there should be some other function to detect the case more precisely besides looking at the error string.

(We are using ent v0.1.1 but the code doesn't appear to have changed significantly since that tag.)

**Comment by a8m** [comment]
Hey @joewreschnig and thanks for reporting this issue! 

Can you add please a partial of the code you use to update entities? Do you use update-one or update-many?

**Comment by a8m** [comment]
Fixed. Thanks for reporting this issue @joewreschnig!

Feel free to open if you still have problems with it.
