### ISSUE TITLE
Doesn't support table prefix function ?

### ISSUE THREAD

**Issue by sohaha** [facebookincubator/ent#344]
Doesn't support table prefix function ?

Useful when there are multiple items in the database.

**Comment by a8m** [comment]
Hey @sohaha, 
Can you please give more details?

There’s an option to provide a custom table name to the schema using [Config](https://entgo.io/docs/schema-config/).

**Comment by sohaha** [comment]
realized this way, thank you!

**Comment by Xwudao** [comment]
@a8m the custom config must set for every schema:

```go

// Annotations of the User.
func (User) Annotations() []schema.Annotation {
    return []schema.Annotation{
        entsql.Annotation{Table: "Users"},
    }
}

```

Is there has a more flexible common function for setting the common table name prefix?

Such as, I set only once in somewhere, and the all schema will auto add the prefix for table name?

**Comment by rotemtam** [comment]
Hey @Xwudao,

Thanks for reaching out. You can use [codegen hooks](https://entgo.io/docs/code-gen#code-generation-hooks) to mutate your schema programmatically before code is generated.

**Comment by Xwudao** [comment]
> Hey @Xwudao,
> 
> Thanks for reaching out. You can use [codegen hooks](https://entgo.io/docs/code-gen#code-generation-hooks) to mutate your schema programmatically before code is generated.

Thx.

**Comment by Xwudao** [comment]
@rotemtam 

Hi, I try to use code below:

```go
// PrefixSchema ensures all fields in the graph have a specific tag name.
func PrefixSchema(name string) gen.Hook {
	return func(next gen.Generator) gen.Generator {
		return gen.GenerateFunc(func(g *gen.Graph) error {
			tables, err := g.Tables()
			utils.CheckErrWithStatus(err)

			for _, table := range tables {
				table.Name = name + table.Name
			}

			//or: 
			//for i := 0; i < len(tables); i++ {
			//	tables[i].Name = name + tables[i].Name
			//}
			return next.Generate(g)
		})
	}
}
```

Both can't update the table name.

How can I do?

**Comment by rotemtam** [comment]
Hey,
Don't try to edit the tables directly, instead add the entsql annotation to each node (entity) and let Ent set the physical table names.

**Comment by Xwudao** [comment]
@rotemtam 
I'm not familiar with 'entc', especially annotation. Can you give me an example? Thank you.

![image](https://user-images.githubusercontent.com/31327868/182317360-b537744d-153a-4c5e-9b3b-a74fc308a994.png)


the schema's annotation is `map[string]interface{}`

But, in other document, it not the same type

https://entgo.io/docs/schema-annotations#custom-table-name

**Comment by a8m** [comment]
Hey! Here is an example hook for adding such an annotation for all nodes.

```go
func(next gen.Generator) gen.Generator {
	return gen.GenerateFunc(func(g *gen.Graph) error {
		for _, n := range g.Nodes {
			a := &entsql.Annotation{Table: fmt.Sprintf("prefix_%s", n.Table())}
			if n.Annotations == nil {
				n.Annotations = gen.Annotations{}
			}
			n.Annotations[a.Name()] = a
		}
		return next.Generate(g)
	})
},
```

Let me know if you need a different example.

**Comment by Xwudao** [comment]
@a8m Thank you very very much!

It resolve my problem.

**Comment by eudore** [comment]
The current version 0.13.1 requires adding a prefix to the Edge ref table.

Running error `running ent codegen: execute template "schema": template: schema.tmpl:26:18: executing "schema" at <$.Tables>: error calling Tables: runtime error: invalid memory address or nil pointer dereference` When the template calls the Tables method with a null pointer, you can execute `g.Tables()` in advance to locate the error.

```golang
func HookTablePrefix(prefix string) gen.Hook {
	return func(next gen.Generator) gen.Generator {
		return gen.GenerateFunc(func(g *gen.Graph) error {
			for _, node := range g.Nodes {
				if node.Annotations == nil {
					node.Annotations = make(gen.Annotations, 1)
				}
				tab := entsql.Table(fmt.Sprintf("%s_%s", prefix, node.Table()))
				node.Annotations[tab.Name()] = tab

				for _, e := range node.Edges {
					e.Rel.Table = fmt.Sprintf("%s_%s", prefix, e.Rel.Table)
				}
			}


			// check create tables err
			g.Tables()

			return next.Generate(g)
		})
	}
```
