### ISSUE TITLE
proposal: hooks

### ISSUE THREAD

**Issue by a8m** [facebookincubator/ent#353]
# Hooks API

We started to work on designing the hooks and the privacy layers for `ent`, and wanted to share with you our initial thoughts before we continue with the implementation.

We currently have 2 design proposals, and we'd like to get a feedback about them. Which one do you prefer to work with, or just random suggestions for improvements.

(Note: both privacy and deletion-api will be using hooks, but they will have a different interface. A simpler one).

---

## view

In both proposals, there's a new concept that is being used named `view`. A `QueryView` that gives a **generic** view of the READ operation that is executed, and a `MutationView` for describing the {CREATE, UPDATE, DELETE} operations.

There's also a `view` per-entity, that provides a **safer** API (e.g. `user.Mutation`).

## Proposal 1: A middleware-like API.

In this proposal there are 2 options for registering hooks. A global hook (that gets the **generic** interface), and it's being executed on all entities, or a per-entity hook (that gets the **safer** interface).

**Global interfaces:**
```go
type (
   Mutator interface {
      Mutate(context.Context, view.Mutation) (ent.Result, error)
   }
   Queryer interface {
      Query(context.Context, view.Query) (ent.Result, error)
   }
)
```

**Per-entity interfaces:**
```go
type (
   Mutator interface {
      Mutate(context.Context, user.Mutation) (user.Result, error)
   }
   Queryer interface {
      Query(context.Context, view.Query) (user.Result, error)
   }
)
```

The idea in this proposal, is to have an API that is similar to the HTTP middleware pattern. An example for a usage looks as follows:

```go
// A rough example for cascading deletion.
func DeletePets(next user.Mutator) user.Mutator {
   return user.MutateFunc(func (ctx context.Context, mv user.Mutation) (user.Result, error) {
      if mv.Operation() != view.Delete  {
         return next.Mutate(ctx, mv)
      }
      // Delete all user pets.
      pets, err := mv.QueryPets()
      if err != nil {
         return nil, err
      }
      // Execute wrapped middleware.
      res, err := next.Mutate(ctx, mv)
      if err != nil {
         return nil, err
      }
      // Delete all pets.
      // ...
      return res, nil
   })
} 
```

The advantage of this pattern, is that it's simpler to share state between the "before" and "after" steps of the operation.

The disadvantage is that it's a bit complicated for newbies (this is just my observation from developing in Go in the last few years). 

(Alex and I prefer this proposal)

## Proposal 2: Before-After API

In this proposal, a hook is registered on each operation (before or after).
It's common in many ORMs outside, and it looks as follows:

```go
type Hook struct{}

func (h *Hook) BeforeCreate(ctx context.Context, mv user.Mutation) error {
   // ...
}

func (h *Hook) AfterCreate(ctx context.Context, *ent.User) {
   // ...
}
```

The advantage of this pattern, is that it's more explicit and easier to understand.

The disadvantages are: it's too verbose, and it's relying on `context.Context` in order to share state between operations ("before" and "after").

---

I tried to give a TL;DR for both proposals, and I'd be happy to hear your thoughts.

**Comment by cliedeman** [comment]
I am having some trouble understanding the Proposal 1 example

```
// A rough example for cascading deletion.
func DeletePets(next user.Mutator) user.Mutator {
   return user.MutateFunc(func (ctx context.Context, mv user.Mutation) (user.Result, error) {
      if mv.Operation() != view.Delete  {
         return next.Mutate(ctx, mv)
      }
      // Delete all user pets.
      pets, err := mv.QueryPets()
      if err != nil {
         return nil, err
      }
      // Execute wrapped middleware.
      res, err := next.Mutate(ctx, mv)
      if err != nil {
         return nil, err
      }
      // Delete all pets.
      // ...
      return res, nil
   })
}
 ```

Is this framework code (generated) or user code?

Proposal 1 can also easily take advantage of `defer` whereas Proposal 2 cannot


Trying to come with ideas to defend Propsal 2....
> The disadvantages are: it's too verbose, and it's relying on context.Context in order to share state between operations ("before" and "after").

The hook struct could have additional variables (Sharing across context is tedious and error prone I think).
```
type Hook struct{
  start time.Time
}

func (h *Hook) BeforeCreate(ctx context.Context, mv user.Mutation) error {
  h.start = ...
   // ...
}

func (h *Hook) AfterCreate(ctx context.Context, *ent.User) {
  // do something with h.start
   // ...
}
```

**Comment by chris-rock** [comment]
Awesome to see this coming in. Can you share an example how you would call the code from the usage perspective. Based on your description, it feels like option 2 is heavily disconnecting business logic from hooks and it may be challenging to maintain them together.

**Comment by a8m** [comment]
> Is this framework code (generated) or user code?

This is a user code. It's just an example to demonstrate how to use hooks. 

> Proposal 1 can also easily take advantage of defer whereas Proposal 2 cannot

Yeah, good point!

> The hook struct could have additional variables (Sharing across context is tedious and error prone I think).

Not really, you register your hooks on the `*ent.Client`, and a client can execute multiple operations concurrently. Hence, this should be thread safe.

**Comment by a8m** [comment]
Thanks for the feedback @cliedeman 

> Is this framework code (generated) or user code?

This is a user code. It's just an example to demonstrate how to use hooks. 

> Proposal 1 can also easily take advantage of defer whereas Proposal 2 cannot

Yeah, good point!

> The hook struct could have additional variables (Sharing across context is tedious and error prone I think).

Not really, you register your hooks on the `*ent.Client`, and a client can execute multiple operations concurrently. Hence, this should be thread safe.

**Comment by a8m** [comment]
Hey @chris-rock! 

> Awesome to see this coming in. Can you share an example how you would call the code from the usage perspective.

Do you mean - how hooks are registered?

If so, we're thinking about 2 options:
(Note: these are just examples, we didn't figure out yet what's the "right" way).  

1. Make it possible to declare hooks on the schema. For example:
  ```go
  // <project>/ent/schema/user.go

  package schema

  import "github.com/facebookincubator/ent"

  // User holds the schema definition for the User entity.
  type User struct {
      ent.Schema
  }

 // Hooks of the User.
  func (User) Hooks() []ent.Hook {
      return []ent.Hook{
            Hook1{},
            view.MutateFunc(...),
      }
  }

  // Fields of the User.
  func (User) Fields() []ent.Field {
      return []ent.Field{
            // ...
      }
  }
   ```

This is useful for running some stateless business logic on queries/mutations. 

2. Register hooks when initializing the `*ent.Client`:

  ```go
  // After calling ent.Open, set up the hooks:
  //
  //  *ent.Client fails if a hook does't match any of the interfaces (in the `view` package). 
  if err := client.Register(h1, h2, h3, ...); err != nil {
      // ...
   }
  ```
This option is necessary for hooks that use dependencies (using DI) or depend on flags/envars before their initialization.

**Comment by cliedeman** [comment]
Thanks for the response @a8m 

> Not really, you register your hooks on the *ent.Client, and a client can execute multiple operations concurrently. Hence, this should be thread safe.

But then we can't actually share variables between the hooks because we would need to return the [updated](https://golang.org/pkg/context/#WithValue) context some how?

For Proposal 1 how would we access the transaction?

**Comment by a8m** [comment]
> But then we can't actually share variables between the hooks because we would need to return the updated context some how?

You're right. I didn't think about this. 

> For Proposal 1 how would we access the transaction?

We thought about this, and we'll need to expose this somehow.

I also want to mention that with the current design, a hook that uses `ent.Tx` (or import the generated `ent` package) needs to be registered when initializing the `ent.Client` and can't be declared in the schema - due to circular dependency (`ent-(imports)->schema-(imports)->hook-(imports)->ent`). 
Some of the types/functions (like `NotFoundError`) will move to a separate package. 

If you have better suggestion, you're welcome to share with us.

**Comment by covrom** [comment]
What about middleware-like (i.e. func(Handler)Handler) style of hooks?

**Comment by covrom** [comment]
Why do we need hooks? We use the API to build the request. At this moment we can use any modifiers. Why do we need to do something implicitly?

**Comment by a8m** [comment]
> Why do we need hooks? 

Hooks are useful for adding logging/tracing/stats globally to `ent`, or add some other business logic to the application. Also, other features are going to be implemented with hooks (internally), like cascading-deletion and privacy support. 

Since, I already have a WIP PR, I suggest that we'll move the conversation to #371.
