### ISSUE TITLE
go build is broken because of the missing WithFixture in release v0.1.2

### ISSUE THREAD

**Issue by xiaofeizhao** [facebookincubator/ent#354]
Hi, `go build ...` is broken because of the missing WithFixture in v0.1.2

```bash
ent/migrate/migrate.go:33:16: undefined: schema.WithFixture
```

A new release could fix this.

**Comment by a8m** [comment]
I think this should solve your problem - https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent
