### ISSUE TITLE
Exception Translation

### ISSUE THREAD

**Issue by cliedeman** [facebookincubator/ent#356]
I would like to implement some basic error translation similar to this [library](https://github.com/Vincit/db-errors)

**Comment by a8m** [comment]
Are you trying to translate the underlying SQL driver errors, or `ent` errors?

**Comment by cliedeman** [comment]
Translate SQL driver errors.

**Comment by a8m** [comment]
I think we can achieve this easily by wrapping the `dialect.Driver` (no codegen changes required).

I'm working on creating another repository `ent-contrib` for sharing helper packages (gqlgen integrations, common templates, etc). We can add this there.

**Comment by cliedeman** [comment]
Sounds good to me

**Comment by sijad** [comment]
@a8m can you please share `ent-contrib` link?

**Comment by BitPhinix** [comment]
@sijad I think it isn't published yet, but I also would love to use it

**Comment by sijad** [comment]
I found it [here 🤫](https://github.com/facebookincubator/magma/tree/3f8322b001d9bb27317b3571267d6f01bff0beae/symphony/pkg/ent-contrib/entgqlgen). it might be outdated.
