### ISSUE TITLE
How can I generate a relationship map？

### ISSUE THREAD

**Issue by caik13** [facebookincubator/ent#364]
I want to generate images like those in the document by command.
Like this.
[image](https://entgo.io/assets/er_traversal_graph.png)
https://entgo.io/assets/er_traversal_graph.png

I'm not good at English. Can you understand what I mean?
thanks.

**Comment by a8m** [comment]
Hey @caik13, we don't have something official and this photo was created manually by me. 
However, we started to work on some schema visualization using d3, that wasn't shipped (my fault), and I hope we can OSS it somewhere in the future (don't want to promise). 

If want to implement something and want guidance, don't hesitate to reach out.
