### ISSUE TITLE
Proposal: How about adding an `entc version` cmd?

### ISSUE THREAD

**Issue by hantmac** [facebookincubator/ent#368]
Sometimes I want to know the current version of `entc`, how about adding the cmd: `entc version` to show it?

**Comment by a8m** [comment]
What's wrong with `go version -m <binary>`? 

I also prefer users to use `go generate` and not `entc` directly, for the reason [mentioned here](https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent).  Especially now, when modules support is ready for production use (since Go 1.14).

**Comment by hantmac** [comment]
> What's wrong with `go version -m <binary>`?
> 
> I also prefer users to use `go generate` and not `entc` directly, for the reason [mentioned here](https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent). Especially now, when modules support is ready for production use (since Go 1.14).

Exactly,  I want to make sure that the version being used by `entc` is identical to the `ent version`, so I wanna to know the `entc` version clearly. As for `go version -m <binary>`, it shows lots of message :
![image](https://user-images.githubusercontent.com/7600925/75441463-aa94c900-5998-11ea-9084-d98c5e946cc6.png)

Okay, I will follow your advice to use `go generate` other than `entc` directly, although `entc` looks more magic and simple 😄 . (In my opinion,  making `entc` more powerfull and easy to use will make developers happy 🍰 )

**Comment by a8m** [comment]
> although entc looks more magic and simple

I agree, but I find myself encounter too many cases where people have "problem" with `ent`, which is basically a version incompatibility between `ent` and `entc`. 

Also, in our cases, we use a lot of codegen-based tools (wire, gqlgen, grpc, swagger, ent, etc), I prefer to give developers one command (`go generate`) that will handle everything for them. 

I still think that the [getting-started](https://entgo.io/docs/getting-started/) guide need to change.

Closing, but feel free to create a PR and update the documentation (I can do it as well later).

**Comment by erikh** [comment]
FWIW this works great, and keys off your `go.mod`:

//go:generate bash -c "go run github.com/facebookincubator/ent/cmd/entc generate --idtype uint64 ./schema && rm example_test.go"
