### ISSUE TITLE
Bug: O2M edge fails during data migration using string id in PostgreSQL

### ISSUE THREAD

**Issue by fitzix** [facebookincubator/ent#372]
`failed creating schema resources: sql/schema: create foreign keys for "cars": pq: foreign key constraint "cars_users_cars" cannot be implemented`

`psql (PostgreSQL) 12.2`

```go
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("id"),
	}
}

// Edges of the User.
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("cars", Car.Type),
	}
}


// Car holds the schema definition for the Car entity.
type Car struct {
	ent.Schema
}

// Fields of the Car.
func (Car) Fields() []ent.Field {
	return []ent.Field{
		field.String("model"),
		field.Time("registered_at"),
	}
}

// Edges of the Car.
func (Car) Edges() []ent.Edge {
	return nil
	// return []ent.Edge{
	// 	edge.From("owner", User.Type).Ref("cars").Unique(),
	// }
}
```

**Comment by hantmac** [comment]
> `failed creating schema resources: sql/schema: create foreign keys for "cars": pq: foreign key constraint "cars_users_cars" cannot be implemented`
> 
> ```go
> type User struct {
> 	ent.Schema
> }
> 
> // Fields of the User.
> func (User) Fields() []ent.Field {
> 	return []ent.Field{
> 		field.String("id"),
> 	}
> }
> 
> // Edges of the User.
> func (User) Edges() []ent.Edge {
> 	return []ent.Edge{
> 		edge.To("cars", Car.Type),
> 	}
> }
> ```

Paste your /ent/schema/car.go, something might wrong with car.go's `Edge` definition.

**Comment by fitzix** [comment]
@hantmac 
whether car edge is `nil` or `from` has the same error, but m2m works.

**Comment by a8m** [comment]
Thanks for reporting this issue @fitzix.  #373 should solve the problem.

**Comment by a8m** [comment]
Also, please note that in this case, if you use `field.String` as a PK, you must limit its size (with `MaxLen`).

Thanks @hantmac for the support as well! It's appreciated.

**Comment by hantmac** [comment]
> Also, please note that in this case, if you use `field.String` as a PK, you must limit its size (with `MaxLen`).
> 
> Thanks @hantmac for the support as well! It's appreciated.

@a8m   HAHA 😄 ，I don’t know if you can open this [link](https://mp.weixin.qq.com/s/Ljp41LdYR9b6RTY85WnBzA). I wrote an article in Chinese to introduce how to use `ent`. Chinese developers are very interested in this. I would like to write more articles about `ent` in Chinese later.

**Comment by fitzix** [comment]
Yes, I noticed that @hantmac is in Shanghai, I am in Beijing. I read a lot of @ hantmac's blogs, he is very good at golang, wrote many articles about go, we are all very interested in ent. 

I think the design of ent It is much more elegant than other traditional orm such as gorm, xorm, they are more or less awkward to use.

But ent is still an early version, and lacks some features like #236, #252, but basically enough, let us look forward to 1.0.

**Comment by a8m** [comment]
> I don’t know if you can open this link. 

Yes I can! Thanks for writing this :smile:.

> But ent is still an early version, and lacks some features like #236, #252, but basically enough, let us look forward to 1.0.

We're currently focus on hooks, privacy and cascading-deletion. Once we finish these, we'll get to #236, #252. 

There are a few open questions about soft-deletion and bulk-creation in order to implement them, but still keep the data correct (in the database). For example, how do we want to handle relationships (foreign-keys, or join-tables).

Thanks again for your contribution guys, and I hope things will get better soon in China.
