### ISSUE TITLE
Column/Table name restrictions

### ISSUE THREAD

**Issue by cliedeman** [facebookincubator/ent#374]
I was testing out an existing database and found some name restrictions

### Invalid Entity Names - [ent namespace functions](https://github.com/facebookincubator/ent/blob/master/examples/start/ent/config.go):
- Driver
- Order
- Debug
- Option

These can be worked around using Config to change the table name and giving the entity a different name

### Invalid column names - [Embedded Config Object](https://github.com/facebookincubator/ent/blob/master/examples/start/ent/config.go#L17):
- driver
- debug
- log

Can be worked around using `StorageKey`. E.g. `field.String("driverName").StorageKey("driver")` 

### Solution?
Not sure if these should be documented and stopped at generate time validation or if they can be made usable

Edit: Added note about reserved keywords

**Comment by hantmac** [comment]
I think documented is enough, adding these hard-code to ent is not graceful 🤔

**Comment by a8m** [comment]
Maybe we can automate this process, but it's in minor priority this moment (until we'll finish hooks and privacy). 

Let's merge this with #284 and #280?

**Comment by NickDubelman** [comment]
Hmmmm, I see this issue was merged with #280, but in the merged solution, I don't see any reference to "Label".

How can I have a field named "label"?
