### ISSUE TITLE
File naming convention – option to specify underscore versus non-underscore

### ISSUE THREAD

**Issue by jufemaiz** [facebookincubator/ent#376]
Currently the name of the file adopts the package name (ref: https://github.com/facebookincubator/ent/blob/0f08a0b5f44d1fdcd0c42fc3390b48690a555580/entc/gen/graph.go#L89).

While naming conventions are diverse, the standard library seems to prefer underscore separated (ref: https://github.com/golang/go/issues/36060).

Given that the generator supports snake case (ref: https://github.com/facebookincubator/ent/blob/0f08a0b5f44d1fdcd0c42fc3390b48690a555580/entc/gen/func.go#L129) would it be possible to either:

1. adopt the convention for filenames; or
2. provide an optional flag to adopt it.

Happy to contributed to see it happen, but wanting to know the feedback from the team first.

**Comment by MaikuMori** [comment]
Have to agree that the naming did make me raise an eyebrow. It's not a huge deal for me, but going with the stdlib convention does seem like the right choice.

**Comment by a8m** [comment]
Hey @jufemaiz and @MaikuMori , and thanks for raising up this issue. 

>  but going with the stdlib convention does seem like the right choice.

Can you given an example of what is not following the Go standard? In `ent`, we generate a package per schema type and name it as lowercase-name (not underscore in packages), and then use this lowercase-name with underscore to the other builders we generate under the `ent` directory.

For example, for schema type named `CreditCard`, the package name is: `creditcard`, and the builder files are: `creditcard_create.go`, `creditcard_update.go`, etc. When looking on the generated assets, it's obvious that the `creditcard` package and `creditcard_*`.go builders are related.

**Comment by MaikuMori** [comment]
I see your point.

What I was referring to is that typically `CreditCard` would be in a `credit_card.go` file. I can see how this would get verbose with longer names.

I noticed this on the files created by `entc init`.

**Comment by a8m** [comment]
> What I was referring to is that typically CreditCard would be in a credit_card.go file.

I'm used to something else, and you can see it in the std in some places as well. For example, [`httputil.ReverseProxy`](https://golang.org/pkg/net/http/httputil/#ReverseProxy) is in the `reverseproxy.go` file. But, I get your point and I think it's just a matter of taste. 

In this case, like I mentioned above:  
> for schema type named CreditCard, the package name is: `creditcard`, and the builder files are: `creditcard_create.go`, `creditcard_update.go`, etc. When looking on the generated assets, it's obvious that the `creditcard` package and `creditcard_*.go` builders are related.

Since we use the same name for the type package/builders/model, and the standard for package names is <i>"lower case, with no under_scores" (-[source](https://blog.golang.org/package-names))</i>, I think it's better to keep it this way.

**Comment by a8m** [comment]
Closing, please free to reopen if you want to continue the discussion.

Thanks!
