### ISSUE TITLE
Can't use float32 

### ISSUE THREAD

**Issue by kryptodirect** [facebookincubator/ent#380]
```
type Company struct {
	ent.Schema
}


func (Company) Fields() []ent.Field {
	return []ent.Field{field.String("name"),
		field.String("address"),
		field.String("address2"),
		field.String("city"),
		field.String("country"),
		field.Float32("account"),
		field.Float32("account2"),
		field.Bool("is_enabled"),
		field.Time("created_at").
			Default(time.Now),
		field.Time("updated_at").
			Default(time.Now),
	}
}

// Edges of the Company.
func (Company) Edges() []ent.Edge {
	return nil
}
```

produces: 

`value.Float32 undefined (type *"database/sql".NullFloat64 has no field or method Float32)`

**Comment by hantmac** [comment]
I feel that there has a bug in `entc/gen/template/dialect/sql/decode.tmpl ` line 102, because  package `database/sql/sql.go` dose not have `sql.NullFloat32`, so we can't use `value.Float32` to generate code, should use `value.Float64`. 
I don't know if what I said is right. If there is any mistake, please correct it.

**Comment by hantmac** [comment]
> ```
> type Company struct {
> 	ent.Schema
> }
> 
> 
> func (Company) Fields() []ent.Field {
> 	return []ent.Field{field.String("name"),
> 		field.String("address"),
> 		field.String("address2"),
> 		field.String("city"),
> 		field.String("country"),
> 		field.Float32("account"),
> 		field.Float32("account2"),
> 		field.Bool("is_enabled"),
> 		field.Time("created_at").
> 			Default(time.Now),
> 		field.Time("updated_at").
> 			Default(time.Now),
> 	}
> }
> 
> // Edges of the Company.
> func (Company) Edges() []ent.Edge {
> 	return nil
> }
> ```
> 
> produces:
> 
> `value.Float32 undefined (type *"database/sql".NullFloat64 has no field or method Float32)`

U can modify `float32(value.Float32)` to `float32(value.Float64)` in `project/ent/company.go` to solve this problem temporarily.

**Comment by a8m** [comment]
Thanks for reporting this issue @kryptodirect. #381 should solve this.
