### ISSUE TITLE
entc generate gives: "load schemas dir: could not determine GOARCH and Go compile"

### ISSUE THREAD

**Issue by huangc28** [facebookincubator/ent#385]
I followed along in the **introduction** section and trying to generate code via schema:

```
// The following works. It generates 
//   - ent/schema/user.go
//   - ent/schema/pet.go
go init User Pet

// go generate failed to work
go generate ent/schema
```
The following error showed.

![Screen Shot 2020-03-12 at 12 12 23 PM](https://user-images.githubusercontent.com/4285184/76486606-c26d5200-645a-11ea-8e9b-e340b5f6a412.png)

My OS is `macOS Catalina version 10.15.3`. Here is the result of my `go env`:

![Screen Shot 2020-03-12 at 12 15 06 PM](https://user-images.githubusercontent.com/4285184/76486700-23952580-645b-11ea-8619-c81e7ee6dc15.png)

`GOARCH=amd64` which i don't think it's the problem.

**Comment by a8m** [comment]
The issues comes from [golang/x/tools/packages](https://github.com/golang/go/issues/30355). 

What is your Go version? - run `go version`

**Comment by huangc28** [comment]
Thanks for the reply, my go version is at 

![Screen Shot 2020-03-12 at 5 39 36 PM](https://user-images.githubusercontent.com/4285184/76507960-9bc61000-6488-11ea-8505-9ab0eb2137f1.png)
