### ISSUE TITLE
 Custom edge column names

### ISSUE THREAD

**Issue by xserve98** [facebookincubator/ent#394]
If you can consider supporting edge of the custom field name?

**Comment by hantmac** [comment]
> If you can consider supporting edge of the custom field name?

I can't get your point. For an example?

**Comment by xserve98** [comment]
Sorry, my English is not very good.

A table exists with many edges, I want to customize their names
`edge.To("cars", Car.Type).StorageKey("cars_id")`

**Comment by a8m** [comment]
Thanks for opening this issue, and thanks @hantmac for your collaboration.

Closing, since this is duplicate of #126. Please, let's continue the discussion there.
