### ISSUE TITLE
entc generate faild

### ISSUE THREAD

**Issue by fr3fou** [facebookincubator/ent#397]
![image](https://user-images.githubusercontent.com/1344906/77076249-3a5bef00-69fc-11ea-89b6-b1e28aa2e0fe.png)

after making a barebones example and following through the getting started i get this error:
```bash
entc/load: # command-line-arguments
.entc/entc_test_ent_schema_1584627138.go:289:47: undefined: ent.Hook
.entc/entc_test_ent_schema_1584627138.go:296:15: schema.Hooks undefined (type ent.Interface has no field or method Hooks)
.entc/entc_test_ent_schema_1584627138.go:298:47: undefined: ent.Policy
.entc/entc_test_ent_schema_1584627138.go:305:15: schema.Policy undefined (type ent.Interface has no field or method Policy)
```

here's the code I have

```go
package schema

import (
        "github.com/facebookincubator/ent"
        "github.com/facebookincubator/ent/schema/field"
)

// User holds the schema definition for the User entity.
type User struct {
        ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
        return []ent.Field{
                field.String("username"),
                field.String("email"),
        }
}

// Edges of the User.
func (User) Edges() []ent.Edge {
        return nil
}
```
running on WSL Ubuntu 18.04 with `go version go1.14 linux/amd64`

**Comment by a8m** [comment]
Hey @fr3fou, and thanks for opening this issue.

I'm pretty sure your `ent` version (in go.mod) and `entc` version are incompatible. 

Please follow [this guide](https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent) and re-open this issue if you still have troubles. 

Thanks!

**Comment by fr3fou** [comment]
yea, that fixed it, I had ran the `go get` command outside my project's folder
