### ISSUE TITLE
invalid (json != longtext) when creating schema resources in mariadb 10.5

### ISSUE THREAD

**Issue by mrasong** [facebookincubator/ent#409]
In mariadb 10.5, type `JSON` is an alias of `LONGTEXT`

once I defined the schema with `field.JSON`, and run client.Schema.Create(ctx), the schemas created successfully.

```go
// Fields of the Source.
func (Source) Fields() []ent.Field {
	return []ent.Field{
		field.JSON("images", []string{}).StructTag(`json:"images"`),
	}
}
```

Howerver, when I added a few fields and running `client.Schema.Create(ctx)` again, it paniced.

```
failed creating schema resources: sql/schema: changing column type for "images" is invalid (json != longtext)
```

**Comment by a8m** [comment]
Hey @mrasong and thanks for raising up this issue.

We didn't test `ent` migration on MariaDB, but we should fix this. I'll try to address this ASAP.

**Comment by mrasong** [comment]
thx
