### ISSUE TITLE
Tree traversal support

### ISSUE THREAD

**Issue by chris-rock** [facebookincubator/ent#416]
Postgres supports an [ltree extension](https://www.postgresql.org/docs/12/ltree.html) that is quite useful for storing tree structures. A great explanation is from [Pat Shaughnessy](http://patshaughnessy.net/2017/12/14/manipulating-trees-using-sql-and-the-postgres-ltree-extension). Has Ent any plans to add support for Ltree?

**Comment by a8m** [comment]
Hey @chris-rock and thanks for opening this issue.
I think we can merge this issue with #277 and continue the discussion there. What do you think?

**Comment by chris-rock** [comment]
I think it is definitely going in the right direction. Lets close it for now and re-open/create a more specific issue once we know more. Thank you @a8m
