### ISSUE TITLE
failed query

### ISSUE THREAD

**Issue by hm0** [facebookincubator/ent#419]
Hello, 
I'm testing ent with the following configuration  / environment:
**mysql 5.7**
**go version go1.14.1 darwin/amd64**

Trying from scratch as explained in https://entgo.io/docs/getting-started/ with the demo I get the following problem: 
2020/04/04 10:25:01 failed querying user cars: sql: Scan error on column index 2, name "registered_at": unsupported Scan, storing driver.Value type []uint8 into type *time.Time
exit status 1

Steps to reproduce:
Schemas:

User
----
package schema
import (
	"github.com/facebookincubator/ent"
	"github.com/facebookincubator/ent/schema/edge"
	"github.com/facebookincubator/ent/schema/field"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("age").
			Positive(),
		field.String("name").
			Default("unknown"),
	}
}

// Edges of the User.
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("cars", Car.Type),
	}
}

Car
----
package schema

import (
	"github.com/facebookincubator/ent"
	"github.com/facebookincubator/ent/schema/edge"
	"github.com/facebookincubator/ent/schema/field"
)

// Car holds the schema definition for the Car entity.
type Car struct {
	ent.Schema
}

// Fields of the Car.
func (Car) Fields() []ent.Field {
	return []ent.Field{
		field.String("model"),
		field.Time("registered_at"),
	}
}

Group
------

package schema

import (
	"regexp"

	"github.com/facebookincubator/ent"
	"github.com/facebookincubator/ent/schema/field"
)

// Group holds the schema definition for the Group entity.
type Group struct {
	ent.Schema
}

// Fields of the Group.
func (Group) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			// regexp validation for group name.
			Match(regexp.MustCompile("[a-zA-Z_]+$")),
	}
}

// Edges of the Group.
func (Group) Edges() []ent.Edge {
	return nil
}

**Already generate the code with entc generate ./ent/schema**

Main
-----
package main

import (
	"context"
	"fmt"
	"log"
	"pepper/ent"
	"pepper/ent/car"
	"pepper/ent/migrate"
	"pepper/ent/user"

	_ "github.com/go-sql-driver/mysql"
)

func QueryUser(ctx context.Context, client *ent.Client) (*ent.User, error) {
	u, err := client.User.
		Query().
		Where(user.ID(4)). // This user is already created in DB
		// `Only` fails if no user found,
		// or more than 1 user returned.
		Only(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed querying user: %v", err)
	}
	log.Println("user returned: ", u)
	return u, nil
}

// Query Cars
func QueryCars(ctx context.Context, a8m *ent.User) error {
	cars, err := a8m.QueryCars().All(ctx)
	if err != nil {
		return fmt.Errorf("failed querying user cars: %v", err)
	}
	log.Println("returned cars:", cars)

	// what about filtering specific cars.
	ford, err := a8m.QueryCars().
		Where(car.ModelEQ("Ford")).
		Only(ctx)
	if err != nil {
		return fmt.Errorf("failed querying user cars: %v", err)
	}
	log.Println(ford)
	return nil
}

func main() {
	client, err := ent.Open("mysql", "root:test@tcp(localhost:3306)/pepper")
	if err != nil {
		log.Fatalf("failed opening connection to mysql: %v", err)
	}
	defer client.Close()

	ctx := context.Background()

	// Run migration.
	if err := client.Schema.Create(ctx, migrate.WithGlobalUniqueID(true)); err != nil {
		log.Fatalf("failed creating schema resources: %v", err)
	}

	var a8m *ent.User
	// Query User
	if a8m, err = QueryUser(ctx, client); err != nil {
		log.Fatal(err)
	}

	// Query Cars
	if err := QueryCars(ctx, a8m); err != nil {
		log.Fatal(err)
	}

}

**Comment by a8m** [comment]
I’m quite sure [this](https://github.com/facebookincubator/ent/issues/224#issuecomment-563077669) should solve your issue.

Closing, but feel free to open if you still have troubles with it.

**Comment by hm0** [comment]
Thanks a lot, that worked.
