### ISSUE TITLE
ID after insert

### ISSUE THREAD

**Issue by sj8m** [facebookincubator/ent#426]
First of all great work, nice orm!
Is it possible to get the id after inserting/creating a new entity?

**Comment by a8m** [comment]
Hey @sj8m and thanks for the feedback!

Did you try to run [this code](https://github.com/facebookincubator/ent/blob/6d15902/examples/start/start.go#L162)?

```go
a8m, err := client.User.
	Create().
	SetAge(30).
	SetName("Ariel").
	Save(ctx)
if err != nil {
	return err
}
fmt.Println("ID:", a8m.ID)
```

Closing, but feel free to open if something doesn't work for you. Thanks!

**Comment by sj8m** [comment]
Thanks! I debugged it and there seems to be something wrong on my side. Thanks for your time, keep up the good work!

On 9 Apr 2020, at 18:56, Ariel Mashraki <notifications@github.com<mailto:notifications@github.com>> wrote:



Hey @sj8m<https://github.com/sj8m> and thanks for the feedback!

Did you try to run this code<https://github.com/facebookincubator/ent/blob/6d15902/examples/start/start.go#L162>?

a8m, err := client.User.
        Create().
        SetAge(30).
        SetName("Ariel").
        Save(ctx)
if err != nil {
        return err
}
fmt.Println("ID:", a8m.ID)

Closing, but feel free to open if something doesn't work for you. Thanks!
