### ISSUE TITLE
Missing Create(int ID) 

### ISSUE THREAD

**Issue by sharpSteff** [facebookincubator/ent#427]
currently there is no possibility to pass an ID to create an entry in the table. (as far as I know)

We have the usecase to receive data which is already indexed, so it would be great to use these indexes as the Entity ID, which saves us an additional field and a lot of additional code.

It would be great to have an extra function like:
`ent.client.MyEntity.Create(id).` 
to pass the ID directly

**Comment by a8m** [comment]
Hey @sharpSteff,
You can provide your own IDs (using `SetID`) if the `id` field is configured in the schema. If it wasn't provided to the builder, the database will generate one for you - see the full [docs](https://entgo.io/docs/schema-fields/#id-field) for more info.

Closing, thanks!

**Comment by sharpSteff** [comment]
@a8m Thanks for the quick response! 
That’s exactly what I was looking for
