### ISSUE TITLE
entc is not vendored

### ISSUE THREAD

**Issue by adnaan** [facebookincubator/ent#430]
As per installation instructions,  running:
```
go get github.com/facebookincubator/ent/cmd/entc
```
in a vendored go modules project(i.e. go.mod + vendor dir) doesn't fetch the sub-packages(entc,cmd/entc). This seems to be the default behaviour(?).

I am using `entc` as as package for generation, as per: https://entgo.io/docs/code-gen/#use-entc-as-a-package.

Consequently running `go generate ./ent` fails with:

```
entc.go:8:2: cannot find package "." in:
	/Users/user/code/project//vendor/github.com/facebookincubator/ent/entc
entc.go:9:2: cannot find package "." in:
	/Users/user/code/project/vendor/github.com/facebookincubator/ent/entc/gen
ent/generate.go:3: running "go": exit status 1
```

```
cd project
ls -la vendor/github.com/facebookincubator/ent
total 112
drwxr-xr-x  12 adnaan  staff    384 Apr 13 15:11 .
drwxr-xr-x   3 adnaan  staff     96 Apr 13 15:11 ..
-rw-r--r--   1 adnaan  staff   1244 Apr 13 15:11 .golangci.yml
-rw-r--r--   1 adnaan  staff   3356 Apr 13 15:11 CODE_OF_CONDUCT.md
-rw-r--r--   1 adnaan  staff   2366 Apr 13 15:11 CONTRIBUTING.md
-rw-r--r--   1 adnaan  staff  11357 Apr 13 15:11 LICENSE
-rw-r--r--   1 adnaan  staff   1858 Apr 13 15:11 README.md
drwxr-xr-x   4 adnaan  staff    128 Apr 13 15:11 dialect
-rw-r--r--   1 adnaan  staff   9685 Apr 13 15:11 ent.go
-rw-r--r--   1 adnaan  staff   1207 Apr 13 15:11 go.mod
-rw-r--r--   1 adnaan  staff  11875 Apr 13 15:11 go.sum
drwxr-xr-x   5 adnaan  staff    160 Apr 13 15:11 schema
```

Ofcourse everything works perfectly on removing the `vendor` directory

**Comment by a8m** [comment]
If you're using `entc` as a package, you don't need the `cmd/entc` package - if you run `go mod vendor` after using `entc` in your code, the `github.com/facebookincubator/ent/entc` package should be in your vendor directory (I just checked this).

`ent` by default works with `cmd/entc` this way - https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent

**Comment by adnaan** [comment]
Thank you for the quick response.

Updated the title to reflect that we only `entc` to be vendored. But I still don't see `entc` in vendor directory. This is what I do:
1.  `go get -u -v github.com/facebookincubator/ent/cmd/entc`
2.  ent/entc.go
```
// +build ignore

package main

import (
	"log"

	"github.com/facebookincubator/ent/entc"
	"github.com/facebookincubator/ent/entc/gen"
	"github.com/facebookincubator/ent/schema/field"
)

func main() {
	err := entc.Generate("./schema", &gen.Config{
		Header: `
			// Code generated (@generated) by entc, DO NOT EDIT.
		`,
		IDType: &field.TypeInfo{Type: field.TypeInt},
	})
	if err != nil {
		log.Fatal("running ent codegen:", err)
	}
}
```
3. ent/generate.go
```
package ent

//go:generate go run entc.go

```
4. `go mod vendor`
5. `go generate ./ent`

```
 go generate ./ent
entc.go:8:2: cannot find package "." in:
	/Users/adnaan/project/vendor/github.com/facebookincubator/ent/entc
entc.go:9:2: cannot find package "." in:
	/Users/adnaan/project/vendor/github.com/facebookincubator/ent/entc/gen
ent/generate.go:3: running "go": exit status 1
```
6. 
```
 ls vendor/github.com/facebookincubator/ent/
CODE_OF_CONDUCT.md CONTRIBUTING.md    LICENSE            README.md          dialect            ent.go             go.mod             go.sum             schema```

**Comment by a8m** [comment]
The `// +build ignore` causes this. I'm pretty sure adding the following line to `ent/generate.go` should solve your problem. 

```go
import _ "github.com/facebookincubator/ent/entc"
```

Let me know if it helped

**Comment by adnaan** [comment]
Ah, I get it.

It's because of the `// +build ignore` instruction `entc` doesn't get vendor-ed. Creating a local `cmd` package with a main entry point does the trick.

I think we need to update the documentation(https://entgo.io/docs/code-gen/#use-entc-as-a-package) to reflect this.

**Comment by fezho** [comment]
I just find another way to solve this issue, maybe a better one. Use build constraint  `// +build tools`, this will be ignored for builds, but included for dependencies. See: https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

So, just add a file: tools/tools.go:

```
// +build tools

package tools

import (
	_ "github.com/facebook/ent/cmd/entc"
)
```

**Comment by till** [comment]
@a8m could the schema tool also create a `tools.go`, or at least highlight this? An alternative would be adding this to the docs.
