### ISSUE TITLE
Default uuid not working

### ISSUE THREAD

**Issue by moh-abk** [facebookincubator/ent#432]
Seems no default `uuid` code is generated;

```
import (
	"github.com/facebookincubator/ent"
	"github.com/facebookincubator/ent/schema/edge"
	"github.com/facebookincubator/ent/schema/field"
	uuid "github.com/google/uuid"
)

func (Table) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New),
		field.Time("expires_at").Default(ExpiresDay),
	}
}
```

**Comment by a8m** [comment]
Hey @moh-abk,
What does it mean "no default code is generated". 

We have code testing exactly this ([1](https://github.com/facebookincubator/ent/blob/master/entc/integration/customid/ent/schema/blob.go#L24), [2](https://github.com/facebookincubator/ent/blob/master/entc/integration/customid/ent/blob/blob.go#L54)) and I've just checked this locally (created another test for this #434) and it's working fine. 


Closing, but please open if you find an actual bug. 
Thanks

**Comment by moh-abk** [comment]
@a8m this line - `https://github.com/facebookincubator/ent/blob/master/entc/integration/customid/ent/schema/blob.go#L24` is not for the `id` field -- the code is not generated for `field.UUID("id", uuid.UUID{}).Default(uuid.New)` where the table `id` field is `uuid`

I get `insert node to table \"table_name\": pq: null value in column \"id\" violates not-null constraint"`

I've to manually add `SetID(uuid.New()).`

**Comment by a8m** [comment]
@moh-abk got it! I just added it to the `id` field #436, and I'll merge this tomorrow.

Thanks for reporting this issue.
