### ISSUE TITLE
Allow specifying TxOptions

### ISSUE THREAD

**Issue by moh-abk** [facebookincubator/ent#433]
How I can pass in `sql.TxOptions{}`? - 

I can see it defined here;

`https://github.com/facebookincubator/ent/blob/6819c0190641790b275932247572a0de18e2663d/dialect/sql/driver.go#L54`

**Comment by a8m** [comment]
Hey @moh-abk,
We actually use `BeginTx` with custom templates, but if can be useful for others I don't mind adding this.

I've created #435 and I'll merge this later today.

Thanks

**Comment by a8m** [comment]
#435 Merged

Closing
