### ISSUE TITLE
Feature: Views, Triggers, Functions

### ISSUE THREAD

**Issue by moh-abk** [facebookincubator/ent#437]
I've gone through the code but don't think it's currently possible to do the below;

- `CREATE VIEW`
- `CREATE MATERIALIZED VIEW`
- `CREATE FUNCTION`
- `CREATE TRIGGER`

for postgres.

**Comment by a8m** [comment]
Thanks for proposing this @moh-abk 

We don't have plans to support stored procedures nor triggers. In my opinion, these 2 can be configured on the database separately and don't need any abstraction.

Regarding views - maybe I miss something, but I don't see why it needs to be in ent. ent provides a graph-like abstraction over the database, and if users want to use an SQL specific feature, they can just use it without `ent`, or they can use [custom templates](https://entgo.io/docs/code-gen/#external-templates) to generate a type-safe API for it. If you go on the 2nd option, you're welcome to share it with us, and we'll consider to add it to the upstream if we'll find it useful for others.

**Comment by moh-abk** [comment]
Makes sense @a8m  -- hooks are sort of functions and triggers.

is there support for `Arbitrary Precision Numbers` - `NUMERIC(precision, scale)`  - `https://www.postgresql.org/docs/10/datatype-numeric.html`?

**Comment by a8m** [comment]
> is there support for Arbitrary Precision Numbers - NUMERIC(precision, scale) - https://www.postgresql.org/docs/10/datatype-numeric.html?

Still no. #277 should make it possible and I'm currently working on this.

Closing
