### ISSUE TITLE
entc/gen: execute template "create"

### ISSUE THREAD

**Issue by SSDUBE** [facebookincubator/ent#447]
I have this schema 

package schema

import (
	"github.com/facebookincubator/ent"
	"github.com/facebookincubator/ent/schema/field"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("user"),
	}
}

// Edges of the User.
func (User) Edges() []ent.Edge {
	return nil
}

When I try to run  entc generate ./ent/schema am getting the below error

entc/gen: execute template "create": template: templates:39:47: executing "create" at <ne $f $.ID>: error calling ne: invalid type for comparison
exit status 1
ent/generate.go:3: running "go": exit status 1

**Comment by cliedeman** [comment]
Think it might be fixed by https://github.com/facebookincubator/ent/pull/446

Can you try on go 1.14?

**Comment by a8m** [comment]
Fixed. See #445.

I'll release a new version. Thanks
