### ISSUE TITLE
Reserved-word "Order" is somehow sup-ideal

### ISSUE THREAD

**Issue by aight8** [facebookincubator/ent#448]
In the aspect of naming your app models, an "Order" is a suitable and common naming for a model. Sadly this keyword is reserved, and there isn't a similar good word for it. I could put together two words (ShopOrder etc.) but that's somehow subideal if I look at my other models naming.

Ideas about renaming the internal "Order": OrderBy, OrderType, Sort etc. I don't look at the context of it in detail but I know the DB's sort-mechanism is meant.

**Comment by a8m** [comment]
Hey @aight8, I actually agree with this.
I've created #449 to solve this - it'll probably be merged tomorrow. 

Thanks

**Comment by a8m** [comment]
Closed with #449
