### ISSUE TITLE
go version -m <binary> not working on alpine

### ISSUE THREAD

**Issue by chris-rock** [facebookincubator/ent#450]
I tried to follow this project guideline to check versions for entc via `go version -n entc`. Unfortunately it turned out to be a bit difficult if you use entc on alpine:

```
docker run -it golang:1.14.2-alpine
/go # go get -u github.com/facebookincubator/ent/cmd/entc
/go # which entc
/go/bin/entc
/go # go version -m /go/bin/entc
/go/bin/entc: go1.14.2
```

Maybe we should reopen the discussion #368?

**Comment by a8m** [comment]
Hey @chris-rock. Great to see you again here.

The [godoc mentions](https://golang.org/pkg/runtime/debug/#ReadBuildInfo) that the build information is available only in binaries built with module support.
I just checked it locally and it's working as expected:
![image](https://user-images.githubusercontent.com/7413593/80210341-43179480-863c-11ea-915c-d17bff5d5bf8.png)


A few months ago I thought about adding `debug.BuildInfo` to entc using `entc version`, but this is equivalent to `go version -m <binary>`.

**Comment by chris-rock** [comment]
I see where you coming from.

Problem: I installed entc preinstalled in my CI/CD environment (since I do not commit generated ent code) and from time to time it breaks because its not compatible with the version in go mod. 

Essentially I need to make sure that the entc binary (from CI/CD) fits with the version in project go mod. At this point a way to achieve that is to compare that both versions match.

I think the current approach will make the usage of entc in CI/CD a bit more complex since every user needs to make use he installs entc in a specific way and then implement custom logic (to extract the entc version from go version output) and to compare versions. I am not 100% sure if the small gain of not having a version number in cli is worth the additional pain for each user.

Maybe there are other methods to check that entc and the code are in sync? How do you make sure the versions match in your internal pipelines?

**Comment by a8m** [comment]
> Maybe there are other methods to check that entc and the code are in sync? How do you make sure the versions match in your internal pipelines?

Yes. It's actually the new default configuration. See: https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent

Basically, you create a `generate.go` file in your project with the following content, and simply run `go generate`, for example: 
```go
// ent/generate.go

package ent

//go:generate go run github.com/facebookincubator/ent/cmd/entc generate ./schema
``` 

The Go compiler will use the same version mentioned in your go.mod file.

Alternatively, you can use `go run github.com/facebookincubator/ent/cmd/entc generate ./schema` from any place in your project and it'll work the same.

**Comment by chris-rock** [comment]
Oh cool, that is great. I'll try the go generate based approach.
