### ISSUE TITLE
Feature: Computed fields

### ISSUE THREAD

**Issue by sijad** [facebookincubator/ent#454]
add ability to add virtual fields to Models which are not stored in database.

```go
// ent/schema/user.go

type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("first_name").,
		field.String("last_name"),
		field.String("full_name").Computed()
	}
}

// ent/user_resolvers.go

func UserFullNameResolver(u User) string {
  return u.firstName + " " + u.lastName
}
```

**Comment by a8m** [comment]
Hey @sijad,
There's an option to do it today using templates, so I'm not so convinced it should be on the schema definition. See: https://entgo.io/docs/schema-fields/#additional-struct-fields

**Comment by sijad** [comment]
yes, I'm not sure why I didn't find it sooner...
thanks!
