### ISSUE TITLE
Question / Feature Request: Entity type specific methods

### ISSUE THREAD

**Issue by aight8** [facebookincubator/ent#458]
### Problem
- Currently I have to wrap a generated ```Model``` to a more specific ```SpecificModel``` and have to unwrap it by an ugly ```model.Base``` whenever I need the the base type either for ent DB interaction or whenever I really need it in the base type. I could do ```model.Update()...Save()``` however I again have to wrap it.
- Same for the already generated ```Models``` (collection type). To implement filter methods etc. would be very powerful.

### Advantages
- Always get from all ent methods my specific model type which includes my *helper methods*.
- No wrapping/unwrapping hell / reflected type problem
- Implement methods so that your models match interfaces. Very powerful.

### Disadvantages
- A common sense is to keep models as simple as possible.
  -  I agree with this it when it comes to implement queries direct in models, to much business logic etc. There are many use cases this makes perfectly sense. Furthermore you must isolate the package which contains the specific model implementation anyway and cannot be the package which uses the generated schema (otherwise you have a circuit dependency), so the isolation is given.

### Implementation Ideas
Same like for the mutators types, the ent schema must be built first.

**schema/model.go** - _entity schema_
```go
package schema

type Model struct {
	ent.Schema
}

func (Model) Config() ent.Config {
	return ent.Config{
		// Table: "...",
		ModelType: models.Model,
		CollectionType: models.Models,
	}
}

// ...
```

**ent/model.go** - _GENERATED schema_
```go
package ent

// ...

type Model {}

// ...
```

**app/models/model.go** - _custom part of the model_
```go
package models

import "ent"

type Model {
   ent.Model
}

// some use cases:

func (Model) Slug() string {
   // ..
}

func (Model) CanEdit(u *ent.User /* or just *User for *models.User */) error {
   // .. for more complex or specific policy checks
}

func (Model) CanDelete(u *ent.User /* or just *User for *models.User */) error {
   // .. for more complex or specific policy checks
}

func (Model) ViewLink() string {
   // ..
}

func (Model) EditLink() string {
   // ..
}

func (Model) RefKey() string { // interface, polymorph relationship stuff...
   return "model:id"
}

// ...
```

**app/models/models.go** - _custom part of a model collection_
```go
package models

import "ent"

type Models {
   ent.Models
}

// some use cases:

func (Models) FilterOnlyActive() Models { // custom filters (returns new slice)
   // ..
}

func (Models) MapReduceCount() []int { // model collection data aggregation
   // ..
}

func (Models) Count() int {
   // ..
}
```

### Question
What's currently the best practice to achieve a similar program flow?
Is it possible with templates maybe?

**Comment by a8m** [comment]
Hey @aight8 and thanks for opening this issue.

The [external-templates](https://entgo.io/docs/code-gen/#external-templates) option was created exactly for this. We also use it a lot internally to generated helpers and integrations to other tools (like GraphQL). 

Let me know if you need help with this.

**Comment by aight8** [comment]
Seems like it's incredible extensible with templates.
It were definitely very useful if it become an own documentation page with some samples.

I studied the ent template part, but currently try to figure out a while how I must name the templates. The template dir is rendered to the generated directory (example.tmpl -> example.tmpl.go), beside I can add custom code by defining some pre-specified template blocks of a node to extend those entities.
The ```entc/template/ent.tmpl``` template seems to be the node (entity / model) template.
There is only one custom template extension point called ```model/fields/additional```, which renders my template to every type definition itself only.

I investigate further, maybe someone can give me some inputs how to solve the case I described in the issue - or how we could improve this?

**Comment by cliedeman** [comment]
There is an example in the repo and here are the [docs](https://entgo.io/docs/code-gen/#external-templates)

https://github.com/facebookincubator/ent/blob/master/entc/integration/template/ent/generate.go
https://github.com/facebookincubator/ent/tree/master/entc/integration/template/ent/template

```
//go:generate go run github.com/facebookincubator/ent/cmd/entc generate --template=./template
```

It might feel a bit odd because all the interface implementors are in the same file.

Example code: https://github.com/facebookincubator/ent/blob/master/entc/integration/template/ent/node.go#L52

But this should do what you need.

**Comment by a8m** [comment]
> It were definitely very useful if it become an own documentation page with some samples.

I'll add another section in entgo.io later this week. Thanks for the feedback

**Comment by roger2hk** [comment]
Hey @a8m. Is there any external template sample for adding a function in the generated model entity?

**Comment by a8m** [comment]
> Hey @a8m. Is there any external template sample for adding a function in the generated model entity?

The templates docs - https://entgo.io/docs/templates

**Comment by roger2hk** [comment]
Thanks. I've read the docs but it doesn't mention how to add a function in an existing generated model entity. I have no clue after drilling down into the following gen template. I wonder if it is possible to do that without creating a new file.

https://github.com/facebookincubator/ent/blob/master/entc/gen/template/ent.tmpl

**Comment by a8m** [comment]
> Thanks. I've read the docs but it doesn't mention how to add a function in an existing generated model entity. 

Here's an example from the docs that adds the `GoString` method for all generated entities. 
```
{{ define "node" }}

{{/* Add the base header for the generated file */}}
{{ $pkg := base $.Config.Package }}
{{ template "header" $ }}

{{/* Loop over all nodes and add implement the "GoStringer" interface */}}
{{ range $n := $.Nodes }}
    {{ $receiver := $n.Receiver }}
    func ({{ $receiver }} *{{ $n.Name }}) GoString() string {
        if {{ $receiver }} == nil {
            return fmt.Sprintf("{{ $n.Name }}(nil)")
        }
        return {{ $receiver }}.String()
    }
{{ end }}

{{ end }}
```

> I wonder if it is possible to do that without creating a new file.

It's not possible. The new file name is derived from the template name.
For example, the template `{{ define "stringer" }} ... {{ end }}` will be generated to file named `stringer.go`.

**Comment by ysaakpr** [comment]
How to check if the node has a specific mixin enabled, and then add custom functions ?
