### ISSUE TITLE
Online schema change

### ISSUE THREAD

**Issue by irahulranjan** [facebookincubator/ent#467]
Hi
Thanks for this awesome project. Is ent migration based on https://github.com/facebookincubator/OnlineSchemaChange?

**Comment by a8m** [comment]
Thanks @irahulranjan!

> Is ent migration based on https://github.com/facebookincubator/OnlineSchemaChange?

No. The migration logic is describe in [entgo.io/docs/migrate](https://entgo.io/docs/migrate/), and we plan to improve it before releasing V1 (it's in our roadmap).
