### ISSUE TITLE
Missing Error Check after iterating over rows

### ISSUE THREAD

**Issue by cliedeman** [facebookincubator/ent#477]
I came across this when working on #469 

I have a query that failed due to a constraint but ent returns the no rows error.

Looks like an additional error check is missing here and I think everywhere else rows.Next is called
https://github.com/facebookincubator/ent/blob/b4255998bf56aac9e8d19800fe1ca7d718f8235d/dialect/sql/scan.go#L32
Like in the example
https://golang.org/pkg/database/sql/#example_Rows

```
        for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			log.Fatal(err)
		}
		names = append(names, name)
	}
	// Check for errors from iterating over rows.
	if err := rows.Err(); err != nil {
		log.Fatal(err)
	}
```

**Comment by a8m** [comment]
Thanks for reporting this @cliedeman!
You're welcome to send a patch for this, or I can take it later today.
