### ISSUE TITLE
Checking for data consistency

### ISSUE THREAD

**Issue by ftomza** [facebookincubator/ent#485]
Hi! 
Whether this module has a consistency check when updating a record. In other words, if the recording version does not match the version of the object being recorded, an error is returned that this object has already been recorded by someone. If this functionality is not available, then I am ready to do it via a mixin with a hook for updating. Just a few questions. 
1. How to get the value of the version field in the hook from the database. 
2. How to get the value of the object version field at the time of update, since this value is empty when the hook is triggered.

**Comment by a8m** [comment]
Thanks for opening this issue @ftomza.

> If this functionality is not available

Not available. 

> How to get the value of the version field in the hook from the database.

Currently, there's no way to load the "old value" of a field. In order to do this, you should load this from the database as follows:
```go
hook.On(
	func(next ent.Mutator) ent.Mutator {
		return hook.CardFunc(func(ctx context.Context, m *gen.CardMutation) (ent.Value, error) {
			version, exists := m.Version()
			if !exists {
				// Version as not set; return or fail.
			}
			id, exists := m.ID()
			if !exists { ... }
			crd, err := m.Client().Card.Get(ctx, id)
			if err != nil { ... }
			//
			// Do the check.
			// 
			return next.Mutate(ctx, m)
		})
	},
	ent.OpUpdateOne, // Evaluate only on "update one" operations.
)
```

> How to get the value of the object version field at the time of update, since this value is empty when the hook is triggered.

It's not empty if it was set in the builder. See the example above. 

If you want to write a "generic" mutator that is being evaluated on all types, remove the `hook.<T>Func` wrapper. More info can be found here: https://entgo.io/docs/hooks

Closing

**Comment by a8m** [comment]
Although I closed the issue, you can feel free to comment/discuss here if you have questions, or you can open it if there's any problem with ent.

Thanks :)

**Comment by ftomza** [comment]
Wow how fast! I didn't expect it! Thanks for the answer! I will try to do, if there are questions, of course I will ask! Thank you for the awesome project! I've been waiting for this type of module to work with data for a long time! You're cool!

**Comment by ftomza** [comment]
Yes I'm trying to make 'generic', and here's my code: 

```golang
package ent_mixin_consistency

type ConsistencyMixin struct {
	LenField int
	mixin.Schema
}

func (m ConsistencyMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Bytes("consist_version").
			Comment("Write consistency version").
			Default(randASCIIBytes(getLenField(m))),
	}
}

func (ConsistencyMixin) Hooks() []ent.Hook {
	return []ent.Hook{
		func(next ent.Mutator) ent.Mutator {
			return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
				if err := consistencyHook(ctx, m); err != nil {
					return nil, err
				}
				return next.Mutate(ctx, m)
			})
		},
	}
}

func consistencyHook(ctx context.Context, m ent.Mutation) (err error) {
	if !m.Op().Is(ent.OpUpdateOne) {
		return
	}
	fmt.Printf("Type: %s, Operation: %s, ConcreteType: %T\n", m.Type(), m.Op(), m)

	return
}

// consistency mixin must implement `Mixin` interface.
var _ ent.Mixin = (*ConsistencyMixin)(nil)
```

Question: how do I get a client for ConsistencyMixin?

**Comment by a8m** [comment]
Hey @ftomza, I've missed these comments yesterday.
Thanks so much for the kind words, it's really fun to read this :) 

> Question: how do I get a client for ConsistencyMixin?

```go
if c, ok := m.(interface{ Client() *ent.Client }); ok {
    client := c.Client()
    // ...
}
```
But this will work only for your project (a specific `ent.Client`). That is, if you try to create a generic ConsistencyMixin (let's say for OSS), it won't work and you'll need to wait until we'll add the option for getting old field values.

I'll update this issue when it's available.

**Comment by ftomza** [comment]
Hey @a8m!  

> I've missed these comments yesterday.

No problem, I think there are so many incidents that need to be answered and help those in need :) 

I also haven't found any solutions for how to get a universal client directly, other than making my own template and adding this functionality to the core level. In the meantime, I will do as part of my project, as suggested above.
I would also like to see support for timerange fields with subsequent implementation of temporality.

PS: And if this is not a secret (the main thing is that the main PM does not read us:)), then when to expect new functionality in particular 'generic'?

**Comment by a8m** [comment]
> PS: And if this is not a secret (the main thing is that the main PM does not read us:)), then when to expect new functionality in particular 'generic'?

Hey @ftomza, it's not a secret. It was added a few days ago ;)
I've added a few examples in `entc/integration` how to work with the new API. Here's one of them, that is similar to your use-case:

```go
package schema

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent"
	"github.com/facebookincubator/ent/schema/edge"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/facebookincubator/ent/schema/mixin"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Mixin of the User.
func (User) Mixin() []ent.Mixin {
	return []ent.Mixin{
		VersionMixin{},
	}
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
	}
}

// Edges of the User.
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("cards", Card.Type),
		edge.To("friends", User.Type),
		edge.To("best_friend", User.Type).
			Unique(),
	}
}

type VersionMixin struct {
	mixin.Schema
}

func (VersionMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Int("version").
			Default(0),
	}
}

func (VersionMixin) Hooks() []ent.Hook {
	type OldSetVersion interface {
		SetVersion(int)
		Version() (int, bool)
		OldVersion(context.Context) (int, error)
	}
	return []ent.Hook{
		func(next ent.Mutator) ent.Mutator {
			// A hook that validates the "version" field is incremented by 1 on each update.
			// Note that this is just a dummy example, and it doesn't promise consistency in
			// the database.
			return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
				ver, ok := m.(OldSetVersion)
				if !ok || !m.Op().Is(ent.OpUpdateOne) {
					return next.Mutate(ctx, m)
				}
				oldV, err := ver.OldVersion(ctx)
				if err != nil {
					return nil, err
				}
				curV, exists := ver.Version()
				if !exists {
					return nil, fmt.Errorf("version field is required in update mutation")
				}
				if curV != oldV+1 {
					return nil, fmt.Errorf("version field must be incremented by 1")
				}
				// Add an SQL predicate that validates the "version" column is equal
				// to "oldV" (it wasn't changed during the mutation by other process).
				return next.Mutate(ctx, m)
			})
		},
	}
}
```

**Comment by ftomza** [comment]
Hi @a8m! How could I miss such a super comment! There is no forgiveness for me!)) 
Thank you and your team for a cool product! 
Do you have any comments about timerange fields?
