### ISSUE TITLE
Feature Request: Custom Table Name

### ISSUE THREAD

**Issue by ppphp** [facebookincubator/ent#503]
Thank you for you excellent work. I have a feature request.
I have to split my database tables into some parts just like sharding by hand, spliting my user table like user_0, user_1, user_2. Is it possible to write code like
```go
client := ent.NewClient(db)
client.Schema.User.Create("user_0")
client.User.Use("user_0").GetX(ctx, 0)
```
or similar practice.

**Comment by a8m** [comment]
Hey @ppphp and thanks for opening this issue.
If you want to define a custom table name (in codegen), you can use the [ent.Config](https://entgo.io/docs/schema-config/#custom-table-name) option. This option overrides the default table name generated by ent.

But, if I get it right, you're looking for a sharding solution and not just a custom table name.
If that's the case, we don't support this at moment. However, maybe you can use [custom templates](https://entgo.io/docs/templates/) to generate this API for you? The custom template option allows to inject custom logic to the codegen.

Sharding support is not in V1, but I expect to see it somewhere in the future.

**Comment by ppphp** [comment]
Thank you. I will try it out.

**Comment by Siceberg** [comment]
@a8m , 
Sorry to bring up this topic again, I got a requirement similar to @ppphp , need to be able to change the table name after generating the code.

Can I override the template "dialect/sql/meta.tmpl", make cons "Table" to var  so that the value of this variable can be set in the code, or is there any other more elegant solution?

**Comment by flisky** [comment]
@Siceberg https://github.com/facebook/ent/blob/4af9a331aeb16e04419ef71e597215dc7a4d1bac/entc/integration/config/ent/schema/user.go#L38-L42

It's currently on master.

**Comment by Siceberg** [comment]
@flisky 
Thanks for your reply,

I thought this could only be used to customize the table name before generating the code, how to use Annotations() to change the table name after generating the code?

**Comment by a8m** [comment]
Hey @Siceberg,
Just to make sure I understand this correctly - do you want to change the table name dynamically on runtime? Do you expect that ent will manage the migration? Because if so, you need to override the `migrate/schema.go` file as well.

**Comment by Siceberg** [comment]
Hi @a8m 
Yes, I have to change the table name dynamically on runtime, but I don’t need to manage the migration through ent.
I want to find a long-term, reasonable and elegant way to achieve it, because many old projects I took over have such a database structure.

**Comment by ppphp** [comment]
> @a8m ,
> Sorry to bring up this topic again, I got a requirement similar to @ppphp , need to be able to change the table name after generating the code.
> 
> Can I override the template "dialect/sql/meta.tmpl", make cons "Table" to var so that the value of this variable can be set in the code, or is there any other more elegant solution?

Changing `Table` to var would cause concurrent problem. Please don't do that.

I dynamically look up the table name for sharding, and the key is to rewrite some methods in template for curd in the `entc/gen/template/dialect/sql/` folder.

For example in `createSpec` of `entc/gen/template/dialect/sql/create.tmpl`:
```go
	_spec.Table = fmt.Sprintf("%v_%05v", _spec.Table, {{ $receiver }}.YOUR_PRIVATE_PROPERTY)
```

and for delete it is in `sqlExec`, for update it is in `sqlSave`
```go
	_spec.Node.Table = fmt.Sprintf("%v_%05v", _spec.Node.Table, {{ $receiver }}.YOUR_PRIVATE_PROPERTY)
```

and in migrate create a method
```go
func (s *Schema) CreateYOUROWNTABLE(ctx context.Context, SHARDINGKEY string, opts ...schema.MigrateOption) error {
	migrate, err := schema.NewMigrate(s.drv, opts...)
	if err != nil {
		return fmt.Errorf("ent/migrate: %v", err)
	}
	ts := []*schema.Table{}
	for _, t := range Tables {
			defer func(t *schema.Table,name string) {
				t.Name = name
			}(t, t.Name)
			t.Name = fmt.Sprintf("%v_%05v", t.Name, SHARDINGKEY)
			ts = append(ts, t)
	}
	return migrate.Create(ctx, ts...)
}
```

And then generate go files with your new written template to substitute the original one.

But the bad thing is that when I bump ent version, I must follow the changes in template.

I don't know whether my solution is good one. @a8m

**Comment by a8m** [comment]
Thanks for this great explanation @ppphp!

> But the bad thing is that when I bump ent version, I must follow the changes in template.
>
> I don't know whether my solution is good one. @a8m

Maybe we can move the "table assignment" part to a separate template, and then you'll need to override one little piece that most likely won't change. Or, we can support for checking if the type implements the `Tabler` interface and then call it - you'll still need to use a template to generate the `Table` method, so I prefer the first suggestion.

**Comment by ppphp** [comment]
> Thanks for this great explanation @ppphp!
> 
> > But the bad thing is that when I bump ent version, I must follow the changes in template.
> > I don't know whether my solution is good one. @a8m
> 
> Maybe we can move the "table assignment" part to a separate template, and then you'll need to override one little piece that most likely won't change. Or, we can support for checking if the type implements the `Tabler` interface and then call it - you'll still need to use a template to generate the `Table` method, so I prefer the first suggestion. WDYT?

Both are ok, because adding a extra class attribute and using it always needs some design. I am not an expert on codegen.

It does not matter because I can do diff work quite quickly now...

**Comment by Siceberg** [comment]
We need to use templates anyway. I think the 2nd one is better for this issue, it provides a unified interface to provide better backward compatibility.

**Comment by xmsz** [comment]
Any good solution?

**Comment by giautm** [comment]
What's your issues?

**Comment by xmsz** [comment]
> What's your issues?

My tables like this
![image](https://user-images.githubusercontent.com/5879146/130173610-85adfb32-0601-4d80-9d1b-96c55ed8d75a.png)

Same entity(struct) but with different table name，and tables is still growing

I want to read table like this way (Some other packages are able to do)
```
db.tableName('fans_message_record_1').Query()
db.tableName('fans_message_record_2').Query()
db.tableName('fans_message_record_....').Query()
```

or
```
db.meta.tableName = fans_message_record_1;
db.Query()

```
