### ISSUE TITLE
Proposal: configurable range of IDs for a single Ent type when using WithGlobalUniqueID

### ISSUE THREAD

**Issue by kkom** [facebookincubator/ent#504]
Could the ID range designated for each Ent type if `WithGlobalUniqueID(...)` is set to `true` be configurable to be larger than 2^32?

Databases can represent IDs with 64 bit integers, which is probably really enough for everyone. But 32 bits give us only ~4.5 billion identifiers for every type, which feels like it could be limiting in some situations (fewer than the number of people on Earth).

At this scale there probably would be other infrastructure problems, but changing the ID range seems like a relatively easy upfront decision to make things potentially much easier further down the line.

E.g. designating say 48 bits for an ID would leave plenty of space for having many Ent types (15 bits => 32k). There could be other tradeoffs, depending on the application profile.

What's your thinking on this? Would be open to a PR changing this?

**Comment by a8m** [comment]
Hey @kkom, 

> But 32 bits give us only ~4.5 billion identifiers for every type, which feels like it could be limiting in some situations (fewer than the number of people on Earth).

@alexsn and I actually discussed about this a few months ago, and thought it's not a real issue - we don't see any situation that a table holds more than 4 billion records. 

Also, the rest of the bits are reversed for the type and sharding information (not supported at the moment). So, potentially, users will be able to store 2^32 records in each shard table and ent will manage the shard-mapping for them. 

> What's your thinking on this? Would be open to a PR changing this?

I don't think it's a real issue, but don't mind to hear other thoughts here.

**Comment by kkom** [comment]
Thanks @a8m!

> Also, the rest of the bits are reversed for the type and sharding information (not supported at the moment). So, potentially, users will be able to store 2^32 records in each shard table and ent will manage the shard-mapping for them.

That's great! And I was wondering where the other 16 or so bits went.

So in the future, one ent type could hold num_shards * 2^32 records? That's a much much better solution than the ad hoc thing I came up with, 100% agreed!

**Comment by a8m** [comment]
> So in the future, one ent type could hold num_shards * 2^32 records? 

Exactly.

**Comment by fgm** [comment]
That's an issue I have in a current project for which I'm considering use of ent : we already tables above 4 billions rows (we use Aurora PostgreSQL on AWS), converted to use 64-bit IDs, and growing fairly fast, so it actually is an issue for some real situations.

At first - naive - sight it seems supporting the ability to have the `32` in `int64(id << 32)` at the end of `WithGlobalUniqueID` be configurable and defaulting to 32 would solve this nicely. But there may be dependencies elsewhere.
