### ISSUE TITLE
Feature suggestion: entc --version command

### ISSUE THREAD

**Issue by kkom** [facebookincubator/ent#506]
I did read https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent but I was still faced with a divergence between the results of running `entc` and `go run github.com/facebookincubator/ent/cmd/entc`. Turns out I didn't rebuild my dev container after upgrading the package, so the old `entc` binary lingered on.

I feel like `entc --version` would have pointed me in the right direction a bit sooner. What do you think? Happy to give it a shot myself.

**Comment by a8m** [comment]
This issue has been discussed here several times. See previous discussions: https://github.com/facebookincubator/ent/issues/450, https://github.com/facebookincubator/ent/issues/368.

Use `go version -m <binary>` if you need the entc version.

**Comment by kkom** [comment]
Oups! Sorry for not having done the research! Thanks for linking the previous issues!
