### ISSUE TITLE
Feature Request: Provide high precision time

### ISSUE THREAD

**Issue by haoxf** [facebookincubator/ent#507]
The current time precision is fixed.
Provide a way to modify time precision.

**Comment by a8m** [comment]
Hey @haoxf,
If you want to use a custom database type, you can use the [`SchemaType` option](https://entgo.io/docs/schema-fields/#database-type). 

Closing, but feel free to open if you think it's needed.

**Comment by haoxf** [comment]
> Hey @haoxf,
> If you want to use a custom database type, you can use the [`SchemaType` option](https://entgo.io/docs/schema-fields/#database-type).
> 
> Closing, but feel free to open if you think it's needed.

Okay, thanks for your quick reply.
