### ISSUE TITLE
User defined "id" fields from Mixins ignored

### ISSUE THREAD

**Issue by enmand** [facebookincubator/ent#512]
If you have a mixin that defines an `"id"` field:

```go
type Mixin struct {
    mixin.Schema
}
func (Mixin) Fields() []ent.Field {
    return []ent.Field{ field.String("id") }
}
```

and have a schema that uses this Mixin:

```go
type Thing struct {
    ent.Schema
}
func (Thing) Mixin() []ent.Mixin {
    return []ent.Mixin{ Mixin{} }
}
```

the generation causes an error in `runtime.go` on compile because `Fields()` is called on an undefined variable (that _should_ be the mixin fields), and the `Mixin` fields (if there are others besides "id") are not configured.

**Comment by a8m** [comment]
Hey @enmand and thanks for reporting this issue.
#515 should solve this issue. Please open if you still have troubles with this.
