### ISSUE TITLE
connection pooling in client.Open 

### ISSUE THREAD

**Issue by hongjic** [facebookincubator/ent#513]
```
// Open opens a connection to the database specified by the driver name and a
// driver-specific data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
```
Here the code says that `Open` just opens one connection. At first I was thinking this is a real connection, but turns out it is not, at least when using mysql dialect.  Internally it calls `sql.Open` from `database/sql` package which actually creates a pool of idle DB connections. 

```

// The returned DB is safe for concurrent use by multiple goroutines
// and maintains its own pool of idle connections. Thus, the Open
// function should be called just once. It is rarely necessary to
// close a DB.
func Open(driverName, dataSourceName string) (*DB, error) {
```

This can lead to people misusing `client.Open` and call `open` and `close` multiple times and cause mysterious problems.  Maybe different database driver use different implementations but I think it's worth updating the comment to tell people what you get is a `virtual` connection and depends on the driver implementation of whether it pools connections automatically.

**Comment by a8m** [comment]
Thanks for raising this issue @hongjic. 
#514 should solve the problem.
