### ISSUE TITLE
Bug: for some ent names, function arguments shadow packages in client.tmpl

### ISSUE THREAD

**Issue by kkom** [facebookincubator/ent#525]
I have an entity called SlackOAuthRequest

`entc` generates invalid code for it, as function argument names shadow package names in some files.

Here are some relevant parts of generated `client.go`:

```golang
import (
(...)
	"api/ent/slackoauthrequest"
(...)
)
```

```golang
// QueryCreatedBy queries the created_by edge of a SlackOAuthRequest.
func (c *SlackOAuthRequestClient) QueryCreatedBy(slackoauthrequest *SlackOAuthRequest) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := slackoauthrequest.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(slackoauthrequest.Table, slackoauthrequest.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, slackoauthrequest.CreatedByTable, slackoauthrequest.CreatedByColumn),
		)
		fromV = sqlgraph.Neighbors(slackoauthrequest.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}
```

Function argument named `slackoauthrequest` shadows the identically named package and results in errors:

```golang
root@53d8f3e0fdee:/workspace/karma/api# go generate ./ent
entc/load: # api/ent
./client.go:739:35: slackoauthrequest.Table undefined (type *SlackOAuthRequest has no field or method Table)
./client.go:739:60: slackoauthrequest.FieldID undefined (type *SlackOAuthRequest has no field or method FieldID)
./client.go:741:56: slackoauthrequest.CreatedByTable undefined (type *SlackOAuthRequest has no field or method CreatedByTable)
./client.go:741:90: slackoauthrequest.CreatedByColumn undefined (type *SlackOAuthRequest has no field or method CreatedByColumn)
./client.go:755:35: slackoauthrequest.Table undefined (type *SlackOAuthRequest has no field or method Table)
./client.go:755:60: slackoauthrequest.FieldID undefined (type *SlackOAuthRequest has no field or method FieldID)
./client.go:757:56: slackoauthrequest.CommunityTable undefined (type *SlackOAuthRequest has no field or method CommunityTable)
./client.go:757:90: slackoauthrequest.CommunityColumn undefined (type *SlackOAuthRequest has no field or method CommunityColumn)
./slackoauthrequest.go:101:47: slackoauthrequest.Columns undefined (type *SlackOAuthRequest has no field or method Columns)
./slackoauthrequest.go:133:54: cannot call non-function slackoauthrequest.Status (type slackoauthrequest.Status)
./slackoauthrequest.go:133:54: too many errors
```

There is something special about the name SlackOAuthRequest, as other ents get really short argument names (`u *User` etc.)

I think that the error lies somewhere here:

https://github.com/facebookincubator/ent/blob/29688a0fa5a6728dfeaafe7db0af19f69d1b3e86/entc/gen/template/client.tmpl#L133

I'm reporting it here before I try figure out what's the proper fix... Likely I'll be much slower than the package authors.

PS: I took a closer look only at client.tmpl, potentially other files have the same problem.

**Comment by kkom** [comment]
`SlackOauthRequest` is fine (as expected really)!

Maybe it is the conventional spelling after all (not sure), but a sequence of two or more capital letter should be probably still correctly handled

**Comment by a8m** [comment]
Thanks for reporting this issue @kkom

**Comment by kkom** [comment]
Hey @a8m – actually the same problem is happening for an ent named `SlackOAuthV2Request`

Btw, name's inspired by:

https://github.com/slack-go/slack/blob/b04b8521281b8e06bd4bb5b9c83a81e2a12e2141/oauth.go#L34-L45
