### ISSUE TITLE
Multiple foreign key UUID failing with `WithX()` eager loading

### ISSUE THREAD

**Issue by jufemaiz** [facebookincubator/ent#532]
Use of UUID foreign keys is failing when using eager loading. Index of foreign keys explicitly set to 0 for all foreign keys.

https://github.com/facebookincubator/ent/blob/master/entc/gen/template/dialect/sql/decode.tmpl#L61-L63

```go
						{{- with extend $ "Idx" 0 "Field" $f "Rec" $receiver "StructField" $f.Name }}
							{{ template "dialect/sql/decode/field" . }}
						{{- end }}
```

Should be amended to:

```go
						{{- with extend $ "Idx" $i "Field" $f "Rec" $receiver "StructField" $f.Name }}
							{{ template "dialect/sql/decode/field" . }}
						{{- end }}
```

**Comment by jufemaiz** [comment]
QQ for the team: if I want to implement this fix locally while the wheels turn at your end, how do I achieve this using the local template override approach? Just add in a file at:

```shell
./ent/gen/template/dialect/sql/decode.tmpl
```
?

**Comment by a8m** [comment]
Thanks for reporting this issue and for the quick fix @jufemaiz.
