### ISSUE TITLE
How do I use select in one-to-many or many-to-many

### ISSUE THREAD

**Issue by Teeoo** [facebookincubator/ent#538]
```golang
err := db.EntGoClient.Order.Query().
		Where(order.ID(orderId)).
		WithChecklist(func(query *ent.ChecklistQuery) {
		query.Select(checklist.FieldID,checklist.FieldCopNo).Scan(context.Background(),?????)
	}).
		WithWaybill().
		Select(order.FieldID,order.FieldAskSuccess,order.FieldCustomsStatus,order.FieldCustomsInfo).
		Scan(context.Background(), &order)
	if err != nil {
                 // 
		return
	}
```

**Comment by a8m** [comment]
Please provide a partial of your schema and what you expect to return from the query.
Also note, that `Select` doesn't work with eager-loading.

**Comment by a8m** [comment]
Closing, please feel free to open if you still have question or need help.

**Comment by hongjic** [comment]
@a8m, any plan to support the `Select`  in eager-loading? This can be critical to performance when fetching a large list of items with eager-loading.
