### ISSUE TITLE
Error handeling for specific errors like not found or unique?

### ISSUE THREAD

**Issue by sj8m** [facebookincubator/ent#539]
How can I handle the errors based on the reason of the error like:

`
if err != nil {
		if err == ent.NotFoundError {
			fmt.Println("Error not found")
		}
		if err == ent.UniqueError {
			fmt.Println("Error email in not unique")
		}
	}
`

**Comment by a8m** [comment]
Hey @sj8m,
I'm not sure I got the question here, but I hope this snippet will help you:

```go
// Constraint errors:
usr, err := client.User.Create().
    SetName("Ariel").
    Save(ctx)
if ent.IsConstraintError(err) {
    // "name" is not unique.
}

// NotFound errors:
usr, err := client.Get(ctx, id)
if ent.IsNotFound(err) {
    // user was not found.
}
```

Please open if you still have troubles.

**Comment by sj8m** [comment]
Thanks men this really helps me out :)

On 10 Jun 2020, at 11:30, Ariel Mashraki <notifications@github.com<mailto:notifications@github.com>> wrote:



Hey @sj8m<https://github.com/sj8m>,
I'm not sure I got the question here, but I hope this snippet will help you:

// Constraint errors:
usr, err := client.User.Create().
    SetName("Ariel").
    Save(ctx)
if ent.IsConstraintError(err) {
    // "name" is not unique.
}

// NotFound errors:
usr, err := client.Get(ctx, id)
if ent.IsNotFound(err) {
    // user was not found.
}

Please open if you still have troubles.
