### ISSUE TITLE
proposal: Add ValidatorError type

### ISSUE THREAD

**Issue by aca** [facebookincubator/ent#546]
Ent has some defined error type and helper function to check if it error match that type.
But when ent failed to create/update resource because of validator failure, there's currently no way to differentiate failure for that (correct me if I'm wrong).
It will be useful to have that kind of error type.

```
u, err := s.db.User.Create().SetUserID(u.UserID).SetUserName(u.UserName).Save(ctx)
if ent.IsValidatorError(err) {
	render.Render(w, r, ErrInvalidRequest(r, err))
	return
}
if err != nil {
	render.Render(w, r, ErrServerError(r, err))
	return
}
```

**Comment by jelmersnoeck** [comment]
We've been needing this as well, and even more detailed information about the underlying validation rule. I've opened a PR to add this: https://github.com/facebookincubator/ent/pull/547

**Comment by a8m** [comment]
Done with #547. Thanks for proposing this issue!
