### ISSUE TITLE
Storagekey on Edges not working

### ISSUE THREAD

**Issue by sj8m** [facebookincubator/ent#555]
I tried using the new storage key function on the edges, but it doesn't work out for me. When I migrate the column names are still generated by ent. I also used your user/pets example and the generated edge name is user_pets instead of owner_id
<img width="407" alt="Screenshot 2020-06-17 at 16 48 26" src="https://user-images.githubusercontent.com/53516395/84913044-5eda6c80-b0ba-11ea-85dc-4643ff18ef69.png">
<img width="343" alt="Screenshot 2020-06-17 at 16 48 45" src="https://user-images.githubusercontent.com/53516395/84913081-69950180-b0ba-11ea-85d2-ed7814a9b143.png">

**Comment by a8m** [comment]
You're right! #556 should solve this.

**Comment by a8m** [comment]
Thanks for reporting this @sj8m.
Please let me know if you still have troubles with this.

**Comment by sj8m** [comment]
First of all thanks for the fast support :) Can I just use the fix now or do you need to release it first?

**Comment by a8m** [comment]
`go get -u github.com/facebookincubator/ent` should solve the problem.

**Comment by sj8m** [comment]
@a8m any tips because my pc is still downloading the old 0.24 without the fix that you made? Or is it possible to release this as a new version?

**Comment by a8m** [comment]
I forgot to add the `@master` to the package path. But I released a new version now (v0.2.5).

**Comment by sj8m** [comment]
Thanks for all the help, had an amazing experience so far with both the package and the support of the maintainers :)
