### ISSUE TITLE
Q: how to add field to edge(relation)?

### ISSUE THREAD

**Issue by aca** [facebookincubator/ent#56]
This looks great.. quite amazing. 

It's a newbie question.
I have User / Groups entity. Users can join multiple groups, and groups can have multiple users. So I think it is M:M relation.
When I define edge between to entitys. user_groups table is automatically generated (mysql).
I need some thing like "role" data ( a user is admin in group ) between user - groups.
I think It is good to be included in user_groups(edge) table.
But I just can't find a way to add field to the edge. Do I have to create another entity for role?

**Comment by alexsn** [comment]
@aca, you currently can't add fields to edges (see [v1 roadmap](https://github.com/facebookincubator/ent/issues/46)).

An possible alternative is to define additional edge between users / groups:
`
func (Group) Edges() []ent.Edge {
    return []ent.Edge{
        edge.To("users", User.Type),
        edge.To("admins", User.Type).Required() // group must have at least one admin,
    }
}
`

**Comment by aca** [comment]
@alexsn missed that one. thanks.

What I need is super_admin(which can be multiple) / admin / user  kind of things.
I've tried workaround you provided / creating role entity but generated results are disappoint.
Too sad I think I should give up this great library for current project..

Is there anyone working on this issue ?

**Comment by alexsn** [comment]
It's not our immediate focus at this time. Note that another possible workaround is to add a new ent in between user / group (user <-> role <-> group) which contains the fields you need. Then you could query as follows: `user.QueryRoles().Where(role.Name("admin"))QueryGroups().All(ctx)`

**Comment by aca** [comment]
![image](https://user-images.githubusercontent.com/50316549/66190141-4d853780-e6c6-11e9-901f-0965a6cc99f5.png)

I tried to add new entity, and this is the result. namespace is the group.
absolutely unnessary table for are generated
user_roles, namespace_roles.
Is this what you are mean?

What about just adding "role" column to the user_groups table and use raw sql query, 
until it is fixed? It will be ugly but, It will make it easier to migrate when this issue is fixed.

**Comment by alexsn** [comment]
We only create edges table for a M:N relation while others get a foreign key. You can mark the role ent as having a unique edge to both user / group so no extra tables will be created for its edges.

**Comment by aca** [comment]
@alexsn Oh Great!
https://github.com/aca/kcreg/tree/master/ent/schema

I think I got what I needed. Thanks for your help!

**Comment by sohaha** [comment]
> @alexsn Oh Great!
> https://github.com/aca/kcreg/tree/master/ent/schema
> 
> I think I got what I needed. Thanks for your help!

What is your solution? The link is no longer accessible

**Comment by aca** [comment]
@sohaha Ent still doesn't support adding field to edges. 
 The problem I had was fixed by this
> We only create edges table for a M:N relation while others get a foreign key. You can mark the role ent as having a unique edge to both user / group so no extra tables will be created for its edges.

```
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("rolebindings", RoleBinding.Type).StructTag(`json:"-"`),
	}
}

func (Namespace) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("rolebindings", RoleBinding.Type).StructTag(`json:"-"`),
	}
}


func (RoleBinding) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("namespace", Namespace.Type).Ref("rolebindings").Required().Unique().StructTag(`json:"namespace"`),
		edge.From("user", User.Type).Ref("rolebindings").Required().Unique().StructTag(`json:"user"`),
	}
}
```

**Comment by sohaha** [comment]
@aca  thank you :)

**Comment by bonafideyan** [comment]
the same question: two entity, message and user, user can read messages, and message can be read by users, so it is a m:m relation, my question is what about I want mark a message is read by a user, if the generated table have a column named read, thing become easy.
