### ISSUE TITLE
How to handle nested structures in ent?

### ISSUE THREAD

**Issue by 404cn** [facebookincubator/ent#560]
For example, I got an json from front-end like this:

```json
{
	"name": null,
	"email": "nobody@example.com",
        "keys": {
            "publicKey": "balabalbalblabsldbalbsdlbasldblasbdlb",
            "encryptedPrivateKey": "asdasdasdaksjheqwjhekjqwhekjqhwkejhqwkje"
        }
}
```

I use ent to init an account with 

```
ent init Account
```

And I want to decode this json to ent.Account, but how to write code about **keys** in Account's Fields function?

```golang
// Fields of the Account.
func (Account) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}),
		field.String("name").
			Optional(),
		field.String("email").
			Match(regexp.MustCompile(`(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})`)).
			Unique(),
		// code about keys
	}
}
```

**Comment by a8m** [comment]
Hey @404cn,
For cases like this, I would use a JSON type. See [docs ](https://entgo.io/docs/schema-fields/#types).

**Comment by 404cn** [comment]
Hey @a8m , thanks for you answer.

I try to write it like this:

```go
type Keys struct { PublicKey, PrivateKey string}

func (Account) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}),
		field.String("name").
			Optional(),
		field.String("email").
			Match(regexp.MustCompile(`(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})`)).
			Unique(),
		// code about keys
                field.JSON("keys", &Keys{}),
	}
}
```

But in generated code the ```Keys``` type is ```*schema.Keys``` and an error here because the generated code didn't import package ```scheme```

**Comment by a8m** [comment]
What version of ent do you use?
Can you try to move the `Keys` object and re-run the codegen? Does it work in this case? 

Thanks

**Comment by 404cn** [comment]
version 0.2.5

Yes, if I remove the ```Keys``` object it will work.

But this json is defined in the front-end, I cant't change it .

What I want to do is only use ```ent.Account``` one struct, decode ```request.Body``` into it, and use it to save data to database.

And now the ```Keys``` object is a nested struct in struct ```Account```, I had a look at doc but still don't know how to make it work.

Although I can write another ```Account``` struct, decode json into it and use ```CreateAccount``` to save this ```Account``` info into ```ent.Account```,  but you know, it looks a bit redundant.

BTW: Sorry for my pool English.

**Comment by a8m** [comment]
> Yes, if I remove the Keys object it will work.

Can you create a small schema to reproduce this (or in a temporary repo)?


> What I want to do is only use ent.Account one struct, decode request.Body into it, and use it to save data to database.

You can decode the request body to this struct, but in order to create it or update an existing one, you must use the relevant builder explicitly as follows:

```go
client.Account.Create().
    SetName(a.Name).
    SetEmail(a.Email).
    // ...
    Save(ctx)
```

If you want to do it with "one command" (like `ScanAndSave(req.Body, ctx)`), you can generate a custom function for you using [external templates](https://entgo.io/docs/templates/) that will call the relevant setters based on your business logic.

**Comment by 404cn** [comment]
Here it is.
I got this json from front-end:
```json
{
	"name": null,
	"email": "nobody@example.com",
        "keys": {
            "publicKey": "balabalbalblabsldbalbsdlbasldblasbdlb",
            "encryptedPrivateKey": "asdasdasdaksjheqwjhekjqwhekjqhwkejhqwkje"
        }
}
```
I can write a struct
```golang
type Keys struct {
    PrivateKey string
    PublicKey string
}

type Account struct {
    Name string
    Email string
    Keys Keys
}
```

And decode json into ```Account```
```golang
_ := json.NewDecoder(request.Body).Decode(&Account)
```
Then use sql statement like```insert into account ...``` to insert account info to database.

----

Now I use ```ent``` and want write code like this:
Scheme:
```golang
// Fields of the Account.
func (Account) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Default(uuid.New),
		field.String("name").
			Optional(),
		field.String("email").
			Match(regexp.MustCompile(`(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})`)).
			Unique(),
                 // assume this will work, this is the part that I don't know how to write
		field.JSON("keys", &struct {
                         PublicKey string
                         PrivateKey string
                 }),
	}
}

```
And the decode part like this, use ```ent.Account```:
```golang
_ := json.NewDecoder(request.Body).Decode(&ent.Account)
```
If I remove the ```Keys``` object from scheme, it will says ```can not decode, missing Keys```
If I don't remove the ```Keys``` object, I don't know how to write Account's scheme............😰😰

And a function ```CreateAccount```:
```golang
func CreateAccount(ctx context.Context, client *ent.Client, account ent.Account) (*ent.Account, error) {
	a, err := Client.Account.
		Create().
		SetName(account.Name).
		SetEmail(account.Email).
                // assume this will work
		SetKeys(account.Keys).
		Save(h.Ctx)
	if err != nil {
		return nil, fmt.Errorf("failed creating account: %v", err)
	}

	return a, nil
}
```

**Comment by a8m** [comment]
Hey @404cn and sorry for the delay.
Let's make it simpler - can you please create a temporary repository for this schema and the stuff that are not working for you and I'll give it a look? You can make it private and send me an invitation.

Thanks

**Comment by 404cn** [comment]
Done

```go
field.JOSN("keys", &struct {PublicKey, PrivateKey string}{}),
```
