### ISSUE TITLE
Question: How to use pgx instead of pg through the standard Go database/sql interface?

### ISSUE THREAD

**Issue by roger2hk** [facebookincubator/ent#563]
The error message is shown as follows when `_ "github.com/jackc/pgx/v4/stdlib"` is added in the `import`. Is `pgx` supported? Did I miss anything?

```go
sql: unknown driver "postgres" (forgotten import?)
```

https://github.com/jackc/pgx/wiki/Getting-started-with-pgx-through-database-sql

The error comes from `database/sql/sql.go` if I use `postgres` as the driver name. If I use `pgx` as the driver name, it is not in the ent's supported driver list.
![image](https://user-images.githubusercontent.com/2505465/85257330-40001f80-b498-11ea-8e35-0a4ef9bdd9a8.png)

**Comment by a8m** [comment]
Hey @roger2hk, 
You can wrap an existing `sql.DB` with `ent.Driver` as follows:

```go
package main

import (
	"context"
	"database/sql"
	"log"

	"<project>/ent"

	entsql "github.com/facebookincubator/ent/dialect/sql"
	_ "github.com/jackc/pgx/v4/stdlib"
)

func main() {
	db, err := sql.Open("pgx", "host=localhost port=5431 user=postgres dbname=test password=pass sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	drv := entsql.OpenDB("postgres", db)
	client := ent.NewClient(ent.Driver(drv))
	// Your code. For example:
        ctx := context.Background()
	if err := client.Schema.Create(ctx); err != nil {
		log.Fatal(err)
	}
	users, err := client.User.Query().All(ctx)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(users)
}

```

**Comment by roger2hk** [comment]
Thanks. It works like a charm. The `.DB()` is missing for converting from `*Driver` to `*sql.DB`.
```go
drv := entsql.OpenDB("postgres", db.DB())
```
