### ISSUE TITLE
Some stringBuilder methods add validators that doesn't work with custom types

### ISSUE THREAD

**Issue by DeedleFake** [facebookincubator/ent#567]
Several of the `field.stringBuilder` add custom validators of the type `func(string) error`. If the user has also called `GoType()`, this will cause a panic in `ent/runtime.go` when it tries to load them because of a failed type assertion.

For example, given the following schema:

```go
type Example struct {
  ent.Schema
}

func (Example) Fields() []ent.Field {
  return []ent.Field{
    field.String("example").
      GoType(new(Base64String)).
      NotEmpty(),
  }
}

type Base64String []byte

func (str Base64String) Value() (dialect.Value, error) {
  return base64.StdEncoding.EncodeToString([]byte(str)), nil
}

func (str *Base64String) Scan(val interface{}) error {
  switch val := val.(type) {
  case string:
    dec, err := base64.StdEncoding.DecodeString(val)
    if err != nil {
      return err
    }
    *str = dec

  default:
    return fmt.Errorf("unexpected type: %T", val)
  }
}
```

Generation works fine for this, but trying to actually import it yields

```
panic: interface conversion: interface {} is func(string) error, not func(schema.Base64String) error

goroutine 1 [running]:
ent.init.0()
        ent/runtime.go:40 +0x12d8
exit status 2
```

Disclaimer: The given line number is wrong. Please ignore it.

This is because in `ent/runtime.go`, a line similar to

```go
example.ExampleValidator = exampleDescExample.Validators[0].(func(schema.Base64String) error)
```

gets generated, but this doesn't work for the `func(string) error` that gets added to the list of validators by these methods.

**Comment by a8m** [comment]
Thanks for reporting this issue @DeedleFake. 
Yes, we should fix this.

**Comment by a8m** [comment]
Fixed.

Note that your custom GoType should be converted to the validator basic Go type.
In this case, you need to implement the `fmt.Stringer` interface for `Base64String`.

Thanks again for reporting this issue.
