### ISSUE TITLE
Question: Exclude fields in queries & eager loaded edges

### ISSUE THREAD

**Issue by fwielstra** [facebookincubator/ent#569]
I have a model that, simplified, has a M2O relationship between a `Post` and a `User` (that is, a `Post` is written by a `User`).

I fetch a `Post` and include the `User` so that in the front-end I can show the user's name right away, using the `.With()` function:

`post, err := cllient.Post.Query().Where(flow.ID(id)).WithCreatedBy().Only(ctx)`

Now my `User` model also has a field `Password`, which is the (sha-hashed) password of the user. Is there a way to exclude this field in the query itself?

Alternatively, there's field in the `Post` database model that contains the user's ID that I could use to fire off a second query, but there too I'm not sure if there's a way to exclude the `Password` field.

I can probably create a wrapper that  does not convert the `Password` field to my application model representation so that it does not escape the database / service layer of my application. But it's easy to miss.

Or is this what's referred to as the Privacy layer in the V1 roadmap?

**Comment by a8m** [comment]
The [.Sensitive()](https://entgo.io/docs/schema-fields/#sensitive-fields) can help you here (I hope it's enough for your case). However, more options like selecting specific fields and control their privacy will be added in the future.

**Comment by a8m** [comment]
@fwielstra - please let me know if the `.Sensitive()` option solved your problem at the moment. If so, let's close this issue, since it's part of our V1 roadmap. 

Thanks!

**Comment by fwielstra** [comment]
Sorry, I was testing it out after adding the reaction.

Hmm, it's still output when I e.g. put the user in a `fmt.Printf()` (but I only use that for debugging anyway; should be careful with logging).

I think for now (given that my application isn't too complex yet) I'll stick to trusting my separation of layers; my HTTP layer doesn't simply output the user object (there's a conversion involved), I can move password validation to my database / service layer, and exclude it when converting it to my 'core' layer if it's not necessary (which it should never be).

Thanks for the quick response!

**Comment by a8m** [comment]
The `fmt` functions, check if the struct implements the `fmt.Stringer` interface before they scan and print the struct, and sensitive fields are omitted in this case (e.g. you'll see `password=<sensitive>` in your logs. See an [example](https://github.com/facebookincubator/ent/blob/052ba492940337d5d0895ca30af183b0e72f076a/entc/integration/ent/user.go#L394).
