### ISSUE TITLE
Required Edge created as nullable FK?

### ISSUE THREAD

**Issue by NickDubelman** [facebookincubator/ent#572]
@a8m In the last comment of [this issue](https://github.com/facebookincubator/ent/issues/167) you say that a Unique edge is still allowed to be nullable. But what about a Required edge? 

I have a simple Todo list and my Todo requires an Author:
```go
func (Todo) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("author", User.Type).Unique().Required(),
	}
}
```

but the generated SQL table allows the `todo_author` column to be null. Is there a reason for this?

```
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| title       | varchar(255) | NO   |     | NULL    |                |
| completed   | tinyint(1)   | NO   |     | NULL    |                |
| todo_author | bigint(20)   | YES  | MUL | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
```

```go
TodosColumns = []*schema.Column{
	{Name: "id", Type: field.TypeInt, Increment: true},
	{Name: "title", Type: field.TypeString},
	{Name: "completed", Type: field.TypeBool},
	{Name: "todo_author", Type: field.TypeInt, Nullable: true},
}
```

It's not a big deal because I'm sure the generated client will do the proper validation, but it would be nice to get this validation at the SQL level (or at least understand why this isnt feasible).

Thanks for the great work!

**Comment by a8m** [comment]
Hey @NickDubelman and thanks for raising up this issue.
Required edges are mandatory on the entity creation (let's say, a pet must be created with an associated owner), but like you mentioned above they are not forced by the database (using the `NOT NULL` clause).
Also note, that for FK columns that are part of entity-tables  (not join tables), we add the `ON DELETE SET NULL` action on the FK creation.

The main reason is that we found it super complex and hard to maintain the schema with these constraints, and I can give an example: let's say you want to delete a user with a O2M to their cars. If you have a `NOT NULL` constraint on the "user_cars" column, you (not the framework) need to delete their cars first. But, let's say these cars are associated with an insurance entity with the same constraint, so you'll need to delete these insurances as well, and what if you have a constraint-loop? 

Cascading deletion support can solve some of the problems here, and it's mentioned in https://github.com/facebookincubator/ent/issues/407.

Having said that, I do plan to give people the option to fully control their schema creation as mentioned in https://github.com/facebookincubator/ent/pull/565#issuecomment-648766102 and https://github.com/facebookincubator/ent/issues/562, and in cases like this, users can choose to define their FKs as non-nullable, but they need to be aware that ent won't be able to magically manage them.

**Comment by NickDubelman** [comment]
Thanks a lot, that was exactly the kind of explanation I was hoping for.

**Comment by a8m** [comment]
> Thanks a lot, that was exactly the kind of explanation I was hoping for.

Great, feel free to post here whenever you have question.

**Comment by NickDubelman** [comment]
Sorry, just want to reopen to ask if the control over schema creation process you are referencing-- will that also allow users to specify cascading deletes?

Wouldn't cascading deletes take care of the issue you brought up regarding constraint-loops?

**Comment by a8m** [comment]
> will that also allow users to specify cascading deletes?

Yes, users will be able to add the `CASCADE DELETE` action to their FKs. However, the cascading deletion we propose in https://github.com/facebookincubator/ent/issues/407 is also not configured on the databases and you can read more about it there.

> Wouldn't cascading deletes take care of the issue you brought up regarding constraint-loops?

**Comment by a8m** [comment]
> will that also allow users to specify cascading deletes?

Yes, users will be able to add the `CASCADE DELETE` action to their FKs. However, the cascading deletion we propose in https://github.com/facebookincubator/ent/issues/407 is also not configured on the database and you can read more about it there.

> Wouldn't cascading deletes take care of the issue you brought up regarding constraint-loops?

I don't have an accurate answer for this (there are multiple dialects). If a user decides to use `CASCADE DELETE` option on the FKs creation, their need to check if that works for them on the database/dialect they use.

**Comment by NickDubelman** [comment]
Yeah, and like you say in the linked issue: if you choose to use cascading delete at DB level, you wouldnt be able to leverage future features like logging all deletes or setting permissions for who can delete certain entities.
