### ISSUE TITLE
schema/field: add the Unique option to the UUID field builder

### ISSUE THREAD

**Issue by moh-abk** [facebookincubator/ent#578]
Just noticed it's not possible to make a UUID field unique. UUID on it's own is unique but its common to have a table where UUID is used in a column other that `id` that relates to another table and you want to ensure its unique.

**Comment by a8m** [comment]
Hey @moh-abk and thanks for reporting this issue.
Yes, we should add the `Unique` option to the `UUID` builder.

You're welcome to send a patch and I'll review it tomorrow, or we'll add this in the upcoming days.
