### ISSUE TITLE
question: properties on edge?

### ISSUE THREAD

**Issue by hongjic** [facebookincubator/ent#586]
I'm using entgo in my new personal project and I really enjoy it so far. 
One pain point I found during development is that there seems no way to define properties on edge.
Do we have plan to support it?

**Comment by a8m** [comment]
Hey @hongjic,

> Do we have plan to support it?

Yes. It's part of our [roadmap task](#46) and I'll open an issue with a proper design proposal before we'll start to work on it. 


Thanks. Closing
