### ISSUE TITLE
schema/field: int field NonNegative not respected by AddField(-1)

### ISSUE THREAD

**Issue by moh-abk** [facebookincubator/ent#596]
defining;

```
field.Int("count").
   NonNegative().
   Default(0),
```

and then repeatedly doing;

```
_, err = tx.SomeModel.
   Update().
   AddCount(-1).
   Save(ctx)
```

is completing and pushing field to `negative` instead of returning an error

**Comment by a8m** [comment]
Hey @moh-abk,
The `NonNegative` is just a syntactic sugar API for defining validators - and validators are executed on values provided in `Set<F>` for create/update. They don't control (or validate) the operations you run on the database. 

If you need something like this, you can use [hooks](https://entgo.io/docs/hooks/) or define your field to be `uint`.
