### ISSUE TITLE
couldn't add edge to index

### ISSUE THREAD

**Issue by noilpa** [facebookincubator/ent#597]
Hi, im trying to create two tables with O2M relation. By default edges creates new fields in table, but i want to create composite index from edge and existing field and i'm fail.

`entc/gen: invalid index for schema "Pet": unknown index field "owner_b"`

Schema to reproduce
```golang
type Owner struct {
	ent.Schema
}

func (Owner) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.New()),
		field.String("name"),
	}
}


func (Owner) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("b", Pet.Type),
	}
}


type Pet struct {
	ent.Schema
}

func (Pet) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
	}
}


func (Pet) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("owner", Owner.Type).
			Ref("b").
			Unique().
			Required(),
	}
}

func (Pet) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("owner_b", "name").Unique(),
	}
}
```

**Comment by a8m** [comment]
Hey @noilpa,
Use the `.Edges()` method to define index on edges (it can be combined with `Fields()`). See [example](https://entgo.io/docs/schema-indexes/#index-on-edges) in the docs.

**Comment by noilpa** [comment]
@a8m thank you
