### ISSUE TITLE
wrong generated tag for the field config

### ISSUE THREAD

**Issue by zeurd** [facebookincubator/ent#598]
Hi, 
I defined a schema with specified jsonapi tags for each field using the StructTag().
eg. I use the tag `jsonapi:"primary,partners"` for the id field.
In the generated code, one extra field is added: config.
This added field has a tag `jsonapi:"-"`
This tag causes the application to fail with error "bad jsonapi tag"
If I remove the jsonapi tag from (and leave the config field) from the generated file, everything works fine

So my question is: would it be possible not to automatically generate this jsonapi tag ?

Thanks in advance for the help

PS: I use this library for jsonapi: https://github.com/google/jsonapi

**Comment by a8m** [comment]
Hey @zeurd and thanks for reporting this issue.

> This added field has a tag jsonapi:"-"

Yes, because `config` is a private field of the generated struct, but we definitely need to fix this. 
Can you please paste here the field definition?

**Comment by zeurd** [comment]
sure:
```
func (Partner) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id").Unique().StructTag(`jsonapi:"primary,partners"`),
		field.Ints("others").StructTag(`jsonapi:"attr,others,omitempty"`),
		field.String("paramx").StructTag(`jsonapi:"attr,paramx,omitempty"`)
```

**Comment by a8m** [comment]
Found the issue - https://github.com/google/jsonapi/issues/33. It happens regardless to your schema.

I'm not sure what jsonapi doesn't support the "-" tag, which is pretty common in Go for ignoring specific fields.
Anyway, it's not an issue in ent. I'll suggest you to either open jsonapi an issue, or just use [custom template](https://entgo.io/docs/templates/) to override the [struct tagging template](https://github.com/facebookincubator/ent/blob/cc6c6e1b4cbb64249cd7de3fad7977c0acc0120b/entc/gen/template/ent.tmpl#L153) in ent.
