### ISSUE TITLE
Create common functions for multiple projects

### ISSUE THREAD

**Issue by javib51** [facebookincubator/ent#599]
Hey there!
First at all, thanks for this amazing project! Something that go was really missing.

I have been recently working in multiple projects in parallel that use ent. As a result, I found myself repeating some pieces of code in all of them.

I would love to create common functions, for example when opening a database connection. This would be a code sample:
```go
import "<your_project>/ent"

func initDatabase(<your args>) *ent.Client {
	var (
		user       string
		password   string
		host       string
		port       string
		schema     string
		dataSource string
	)

	// Init values...
	dataSource = fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?parseTime=True", user, password, host, port, schema)

	// Open database connection
	client, err := ent.Open("mysql", dataSource)
	if err != nil {
		log.Fatal(err)
	} else {
		log.Println("Database connected")
	}

	return client
}

```

I thought that a solution might be to use the interface that defines ent.Client with [exported identifiers](https://golang.org/ref/spec#Exported_identifiers). So using a common function for it, would look similar to this:

```go
import (
    _"<your_project>/ent"
    "<your_project>/ent"
   "ent/utils"
)

func initDatabase(<your args>) *ent.Client {
	client := utils.defaultInitDB(<your args>)
}

```

 However, I didn't find an interface for ent.Client, I am not sure if it exists at all. Any thoughts? Is it possible to do what I am proposing? Or any other idea?

**Comment by xserve98** [comment]
I'll recommend you to use [templates](https://entgo.io/docs/code-gen/#external-templates). For example:


{{ define "external" }}
package ent

func initDatabase(<your args>) *Client {
	....
}
{{ end }}

**Comment by a8m** [comment]
Hey @javib51 and thanks for opening this issue.

`ent.Open` is a package function and there's no way to use an interface here. However, like @xserve98 suggested, using [templates](https://entgo.io/docs/templates/) is the right approach here. Please let me know if you need further help with this.

Thanks @xserve98 for your engagement - it's appreciated!
