### ISSUE TITLE
Different name for ID field in struct

### ISSUE THREAD

**Issue by aakhan1** [facebookincubator/ent#603]
Is it possible to define a different name for the ID field in the entity struct.   I'd like to match this up with my proto definition somewhat.

**Comment by a8m** [comment]
Hey @aakhan1,
We don't support this. However, the [struct-tags](https://entgo.io/docs/schema-fields/#struct-tags) option is used to add meta data for other third-party tools/libraries integration - you should check if the package you use supports this. 

Closing as we don't have plan to add this functionality.
