### ISSUE TITLE
Proposal: use pgx as PostgreSQL driver

### ISSUE THREAD

**Issue by ernado** [facebookincubator/ent#605]
What about using https://github.com/jackc/pgx instead of https://github.com/lib/pq?

From pg README:
> This package is effectively in maintenance mode and is not actively developed. Small patches and features are only rarely reviewed and merged. We recommend using pgx which is actively maintained.

**Comment by a8m** [comment]
Hey @ernado, thanks for opening this issue - I didn't know the project status was updated :neutral_face:.
What do you mean by "using pgx"? ent uses pg only for testing purposes. 

If you want to use pgx, there's an example how to use it in the docs: https://entgo.io/docs/sql-integration/#use-pgx-with-postgresql

**Comment by ernado** [comment]
Oh, I missed that part, sorry :(
Thank you!

Probably we can use `pgx` directly for speed or postgresql-specific features, closing this for now.
