### ISSUE TITLE
Adding new unique UUID with default

### ISSUE THREAD

**Issue by ernado** [facebookincubator/ent#609]
I'm trying to add unique UUID field to my schema as follows:
```go
func (Video) Fields() []ent.Field {
	return []ent.Field{
		// ...
		field.String("name").MaxLen(512).Optional(),
		field.UUID("uuid", uuid.UUID{}).
			Default(uuid.New).
			Unique().
			Comment("UUID for public API"),
	}
}
```

First, I've tried to do it via `Indexes()`
```go
func (Video) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("uuid").Unique(),
	}
}
```

But seems like it is not supported for single field :(
Ent is starting to generate migrations like these:
```sql
BEGIN;
CREATE UNIQUE INDEX "video_uuid" ON "videos"("uuid");
COMMIT;
```
And then after applying `CREATE`:
```sql
BEGIN;
DROP INDEX "video_uuid";
COMMIT;
```
And again, and again.

When trying to achieve it via unqie field I'm getting `entc/gen: create type Video: unique field "uuid" cannot have default value`

How can I add my `uuid` field?

**Comment by a8m** [comment]
Hey @ernado and thanks for reporting this issue. 

#610 should fix this :)

**Comment by ernado** [comment]
Thank you! 

Probably we should also forbid creating unique indexes on single column. Seems like database introspection reports such columns as non-unique, but in target schema they are unique, so ent tries to migrate and ends up in failed state with eternal migrations.

**Comment by a8m** [comment]
Agree. Also, unique columns are already indexed.
