### ISSUE TITLE
B: Generator uses wrong import paths when targeting a different directory

### ISSUE THREAD

**Issue by mk0a1a** [facebookincubator/ent#61]
The generator uses wrong import paths when targeting a different directory.

To reproduce:

1. Create entity to `./schema` at directory root

    ```bash
    entc init --target schema Test
    ```

2. Generate code to a target directory

    ```bash
    entc generate --target ent ./schema
    ```

Directory structure should look like this:

- `ent/*` (for generated files)
- `schema/test.go` (entity file)
- `go.mod`
- `go.sum`
- `main.go`

Program won't compile due to wrong import paths in `ent/test_*.go` files.

For example, the import path used in `ent/test_query.go`:

```go
package sample

import (
    ...

	"gitlab.com/user/sample/predicate"
	"gitlab.com/user/sample/test"
)
```

When it should be:

```go
package sample

import (
    ...

	"gitlab.com/user/sample/ent/predicate"
	"gitlab.com/user/sample/ent/test"
)
```

**Comment by a8m** [comment]
In the current implementation, the `schema` package should sits under the `ent` package (i.e. `./ent/schema`). This way, all `ent` code sits under the same directory. 

We should allow users to define a different directory structure. I'll handle this.

**Comment by mk0a1a** [comment]
The problem I had with the default structure is that the generator does not remove old files. If I had an entity called `Dog` then later decide to either rename/delete it, the old `Dog` generated files remain in the `ent` package.

So I figured I'd move the `schema` folder outside the `ent` generated folder so that I can delete `ent` and regenerate the folder through the CLI. Then I came across this issue.

Currently, I went back to the default directory structure and use a simple bash script to remove all generated files in the `ent` folder except for the `schema` folder:

`generate.sh`
```bash
#!/bin/bash

shopt -s extglob
rm -rf ent/!(schema)
entc generate ./ent/schema
```

**Comment by gorda** [comment]
Do you have a [translation](https://docusaurus.io/docs/en/translation) plan for other languages?

**Comment by ryan-hixcare** [comment]
I have same problem as well. We might want delete generated file function out-of-the-box in the CLI.
