### ISSUE TITLE
Provide a unified interface for `create` and `update`

### ISSUE THREAD

**Issue by haoxf** [facebookincubator/ent#626]
When `create` and `update` a entity, currently we should write the same code twice.

Desired result:

var u UserUpdate
if update {
  u = client.User.UpdateOne(...)
} else {
  u = client.User.Create()
}
u.SetName(...)
u.SetAge(...)
...

**Comment by a8m** [comment]
Hey @haoxf,
Please use mutations - https://entgo.io/docs/crud/#mutation
