### ISSUE TITLE
How to get edge id without actual db query

### ISSUE THREAD

**Issue by flamedmg** [facebookincubator/ent#630]
Let's consider your belover PET - > User example.  Let's say i have Pet object and would like to know it's user id for other needs. How do i do that without querying user?

**Comment by a8m** [comment]
Hey @flamedmg, the generated API doesn't expose this option, but you can add it to your code using custom templates.

The other alternatives are - query only the id field as follows:
```go
id, err := p.QueryOwner().OnlyID(ctx)
```

or, use eager-loading and the owner relationship will be populated to the `Pet.Edges` object.

**Comment by dilipkk-foyernet** [comment]
We also need this feature. Looks like this the file needs to be updated https://github.com/facebook/ent/blob/master/entc/gen/template/ent.tmpl but not getting how and where **"user_pets"** (https://github.com/facebook/ent/blob/master/examples/o2m2types/ent/pet.go#L28) field is getting generated, we just need to add one OwnerID method to **\*Pet** which exposes this field.
@a8m can you guide me on how to achieve that?

**Comment by dilipkk-foyernet** [comment]
@a8m  I had take look at that one before using external templates for this purpose and I want to create pull request to entc itself so that it is beneficial for everyone, I was trying to find the code where "user_pets" field is generated but I couldn't find in the code base, once I understand that then I can generate a method on base field model struct.

**Comment by dilipkk-foyernet** [comment]
@a8m I got it, it is happening in https://github.com/facebook/ent/blob/master/entc/gen/graph.go right?

**Comment by a8m** [comment]
Use edge-field: https://entgo.io/docs/schema-edges/#edge-field

**Comment by ofey404** [comment]
> Use edge-field: https://entgo.io/docs/schema-edges/#edge-field

It simply works. Glad to see this old problem has a new solution, also cc @dilipkk-foyernet 

(And I was surprised by your really quick reply XD)
