### ISSUE TITLE
How to generate a template for each Nodes

### ISSUE THREAD

**Issue by deyforyou** [facebookincubator/ent#641]
hi everyone,
I want to generate a template for each Nodes like my %s_service.tmpl for User Group Category and now I get:
user_service.go, group_service.go and category_service.go

I see each template has like value *gen.Graph. Help me please

thank you

**Comment by a8m** [comment]
Hey @deyforyou,
There's no option to generate a separate file for each node-type in the `ent` directory. Instead, you use one template for generating one file for all different types (Usually, you create a template file per logic/API).  For example, see the [`node.tmpl`](https://github.com/facebookincubator/ent/blob/875e6e5/entc/integration/template/ent/template/node.tmpl) and its [`output (node.go)`](https://github.com/facebookincubator/ent/blob/875e6e5/entc/integration/template/ent/node.go).

If you want to add a template output for each type package (e.g. `ent/user/user.go`), name your template as ["meta/additional/*"](https://github.com/facebookincubator/ent/blob/04859c6/entc/gen/template/meta.tmpl#L139). For example, see [`meta.tmpl`](https://github.com/facebookincubator/ent/blob/04859c6/entc/integration/ent/template/meta.tmpl#L1) template. 

Closing, thanks 😃
