### ISSUE TITLE
Generated each template node

### ISSUE THREAD

**Issue by deyforyou** [facebookincubator/ent#642]
generate a template for each node
ex: for a template service.tmpl  with nodes User Group Category generate:
     - user_service.go
     - group_service.go
     - category_service.go

now we have *gen.Graph value template
if we can add value template *gen.Node

**Comment by a8m** [comment]
Hey @deyforyou and thanks for proposing this.
As I commented in https://github.com/facebookincubator/ent/issues/641#issuecomment-664535621, you can use a template named `services.tmpl` and generate a `services.go` file for holding all node services (`UserService`, `GroupService`, etc) - what's the problem with it?

There's no other option at the moment, except creating a template-per-type which is unreasonable. If you think there are better ways to handle it, you're welcome to share your thoughts. 

Closing, thanks.
