### ISSUE TITLE
Please provide API that allow us to use our own DB object

### ISSUE THREAD

**Issue by pjebs** [facebookincubator/ent#65]
Please provide API for us to inject our own *DB object.

This will require an interface of:

```
type SQLBasic interface {
    ExecContext(ctx context.Context, query string, args ...interface{}) (stdSql.Result, error)
    QueryContext(ctx context.Context, query string, args ...interface{}) (*Rows, error)
    QueryRowContext(ctx context.Context, query string, args ...interface{}) *Row
}
```

Maybe another interface for transactions (not required, if we can pass our own *Tx object)

Currently I can't use this package with my https://github.com/rocketlaunchr/mysql-go which is required to make long mysql queries cancellable (respect context cancellation)

**Comment by alexsn** [comment]
Provided that you have a *sql.DB instance which supports mysql dialect you can instantiate ent.Client from it as follows:
```
import (
    stdsql "database/sql"

    <your_project>/ent
    "github.com/facebookincubator/ent/dialect/sql"
)

func ClientFromDB(db *stdsql.DB) *ent.Client {
    drv := sql.OpenDB("mysql", db)
    return ent.NewClient(ent.Driver(drv))
}
```

**Comment by pjebs** [comment]
This approach is not idiomatic Go. 

You should just allow us to pass an object that supports the minimal interface required for `ent` package to work. It is unusable at the moment. There is no way to properly cancel a long-running mysql query.

**Comment by alexsn** [comment]
Implement [dialect.Driver](https://godoc.org/github.com/facebookincubator/ent/dialect#Driver) interface, after which instantiate `ent.Client` with `ent.NewClient(ent.Driver(<your_driver>))`.

**Comment by a8m** [comment]
Closing this issue. Feel free to open if you still have a problem with it.

**Comment by pjebs** [comment]
Can you send me a link to your code where you have implemented your wrapper for stdSql.DB to exactly where you are translating 
`Exec(ctx context.Context, query string, args, v interface{}) error`

`args` and `v` to `args ...interface{}` and `Result` as required by stdSql.Db.

In order to cancel a Mysql query, you have to have a stdSql.Conn object. Your package directly uses the pool.

I am trying to follow your instructions to feed in a Conn object which I have derived from an external stdSql.DB (pool). That is only way.

**Comment by alexsn** [comment]
The code where we implement the dialect.Driver interface is [here](https://github.com/facebookincubator/ent/blob/95210005341f2b397d37449935a52a6764ab15f6/dialect/sql/driver.go#L19).
