### ISSUE TITLE
Error passing through Instrumented SQL for logging

### ISSUE THREAD

**Issue by austincollinpena** [facebookincubator/ent#656]
I'm trying to log queries as they come out through Instrumented SQL. After I register the logger I get an error:

Code:

```
time="2020-08-03T09:14:55-07:00" level=fatal msg="Failed creating schema resources: unsupported driver: \"instrumented-postgres\"" service=go-reverse-proxy
```

```go
	pgLogger := instrumentedsql.LoggerFunc(func(ctx context.Context, msg string, keyvals ...interface{}) {
		message := fmt.Sprintf("%s %v", msg, keyvals)
		// Filter useless messages
		containsNil := strings.Contains(message, "[err <nil> duration")
		containserrEof := strings.Contains(message, "[err EOF duration 0s]")
		if containsNil == true || containserrEof == true {
			return
		}
		log.Printf("%s %v", msg, keyvals)
	})

	sql.Register("instrumented-postgres", instrumentedsql.WrapDriver(&pq.Driver{}, instrumentedsql.WithLogger(pgLogger)))

	Client, err = ent.Open("instrumented-postgres", credentials)
```

Is it possible to use Instrumented SQL with ent go?

**Comment by a8m** [comment]
0Hey @austincollinpena and thanks for raising up this issue. 

I think one of the examples in this [doc](https://entgo.io/docs/sql-integration/#use-pgx-with-postgresql) can help you to set up a custom SQL driver for your ent client.

**Comment by a8m** [comment]
Closing. Feel free to re-open if you still need help.

**Comment by austincollinpena** [comment]
@a8m Thank you for the help, that worked great.

Love the library! Bringing my first Go App to production with it!
