### ISSUE TITLE
proposal: generate Administration Handler for schema

### ISSUE THREAD

**Issue by najBaby** [facebookincubator/ent#658]
If you can add a part **Administration** in package **ent**.
this will be wonderful. thank you

**Comment by a8m** [comment]
Hey @najBaby,
Can you please add more details about this proposal?

**Comment by najBaby** [comment]
Hey @a8m, thank you to answer
we have already all tools to access to database. But If we can have a view of this Like Django

**Comment by a8m** [comment]
Do you mean something like [Django-admin](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/)? If that's the case, I don't think we'll get to it in the foreseeable future. However, I think it's something nice that can be developed as a separate project, and ent can use it as an extension (using external-templates for example).

**Comment by najBaby** [comment]
Yes it's that. But we can generate a template html for each schema like template select, insert...
And i'm sorry to my english expression. I speak french

**Comment by a8m** [comment]
> Yes it's that. But we can generate a template html for each schema like template select, insert...

Agree, but like I mentioned, some tasks have higher priority at the moment - like improving the schema migration (support edge migration), entql, finish the privacy layer, cascading deletion, and more.

If someone is willing to work on this (as a separate project), they can implement it today using [custom external templates](https://entgo.io/docs/templates/).

> And i'm sorry to my english expression. I speak french

Don't be sorry, English is not my first language either (I speak Hebrew) - you should feel free to write here whenever you need or want, this is how we grow and get better.

Closing, but you can feel free to continue the discussion 😃

**Comment by masseelch** [comment]
I indeed currently am developing something like that. I create simple crud handlers for `net/http` using external templates. It is far from ready (not a single test so far). 

I will post a link when i reached a state where it can be useful to others.

**Comment by najBaby** [comment]
Thank you. I will be happy to see this projection.

**Comment by masseelch** [comment]
@najBaby You can follow the progress [here](https://github.com/masseelch/go-api-skeleton).

**Comment by diazoxide** [comment]
Take a look at [ent-refine](https://github.com/diazoxide/ent-refine)
