### ISSUE TITLE
Feature: Ping to find out if DB Connection is alive

### ISSUE THREAD

**Issue by zzerjae** [facebookincubator/ent#661]
Hi,

Thanks for your works for this awesome project. While writing code with the pleasure of learning something new, I thought it would be nice if one feature was added.

I usually check if the connection is made right after I make a DB connection when starting the server. In Ent, it seems that I can't check whether the connection with the DB is properly.

in `database/sql`,  comment on `Open()` says "Open may just validate its arguments without creating a connection to the database. To verify that the data source name is valid, call Ping." So, If the ping method is added to the client, it will be able to perform the desired function.

#### Expected usage
```go
func NewDB() (*DB, error) {
	client, err := ent.Open("mysql", "id:pw@tcp(localhost:3306)/db?parseTime=true")
	if err != nil {
		return nil, errors.Wrap(err, "db.NewDB")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
	defer cancel()
	err := client.Ping(ctx)
	if err != nil {
		return nil, errors.Wrap(err, "db.NewDB")
	}

	return &DB{client: client}, nil
}
```

If these suggestions are okay, I will make a PR. If there is anything I am missing, please let me know. Thank you for making this wonderful open source.

**Comment by a8m** [comment]
Hey @zzerjae! It's great to hear that you enjoy this project 😃 

About your proposal - the [`Ping`/`PingContext`](https://golang.org/pkg/database/sql/#DB.Ping) method already exists in the [`sql.DB`](https://golang.org/pkg/database/sql/#DB) object, so I'm not sure it's really needed it ent.

If you need to call `Ping` only in start-up of the application, I'll suggest you to see this example - [configure-sqldb](https://entgo.io/docs/sql-integration/#configure-sqldb). If you need to call it in many places in the application, I'll suggest you to add this logic to the client using [external-templates](https://entgo.io/docs/templates/) - let me know if you need help with the second option.

**Comment by zzerjae** [comment]
Thanks, @a8m.

I admire your quick feedback. example - [configure-sqldb](https://entgo.io/docs/sql-integration/#configure-sqldb) that you suggested was exactly what I was looking for. Thank you for your kind guidance.

**Comment by a8m** [comment]
Great!

Closing, but feel free to open if it's needed.

**Comment by till** [comment]
@a8m sorry to revive this, I looked at the configure sql-db bit, but I am in a somewhat of a different situation.

It seems, that it's currently not possible to get the driver once `*ent.Client` is created. Or am I missing something? 

I was hoping for something like:

```go
client, err := ent.Open(
	"postgres",
	fmt.Sprintf("host=%s port=%s user=%s dbname=%s password=%s sslmode=disable",
		host,
		port,
		username,
		database,
		password,
	),
)
if err != nil {
   panic(err)
}

// check
err = client.GetDriver().Ping()
// etc. pp.
```

I am creating `*ent.Client` during service bootstrap, I know I could probably do the _heavier_ lifting of creating the driver myself and then maintaining a reference to it as well. But is the opposite possible? Or would you object to a PR to add a `GetDriver()` to the mix?

**Comment by a8m** [comment]
Hey @till! Why not extend the `ent.Client` using a custom template (or a static file) for this?

```go
func (c *Client) Ping() error {
	db := c.driver.(*sql.Driver).DB()
	return db.Ping()
}
```

**Comment by till** [comment]
@a8m if you ask why — because 🤯 . I had no idea this is possible.

I am currently using `go generate ./...` to build everything.

And `entc.go` contains this:

```go
//go:build ignore
// +build ignore

package main

import (
	"log"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

func main() {
	err := entc.Generate("./schema", &gen.Config{
		Features: []gen.Feature{gen.FeatureVersionedMigration},
	})

	if err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}
```

Where would the `--templates` flag go?

**Comment by till** [comment]
Or how would a static file work? Sorry, this may be a total noob question.

**Comment by till** [comment]
Or wait, that was a noob question, I create file in `ent/custom.go` and put it in there. I had no idea this was possible, but of course this makes sense. Thanks so much.

**Comment by fdouglis** [comment]
I tried using that as custom.go, but I couldn't figure out how to get go/ent to be satisfied by the use of `*sql.Driver` -- it would say sql.Driver wasn't defined.  Bitrot, or am I simply not finding the right include?  

I tried the following includes to no avail:

```
 	_"database/sql"
	_"database/sql/driver"
	_ "github.com/go-sql-driver/mysql"
```

This is `go1.22.3`  and `entgo.io/ent v0.13.1```

**Comment by karatekaneen** [comment]
@fdouglis This is my entire `ent/client_healthcheck.go`, hope it solves your error:

```go
package ent

import (
	"context"
	"errors"

	"entgo.io/ent/dialect/sql"
)

var ErrInvalidDriver = errors.New("invalid driver")

func (c *Client) Ping(ctx context.Context) error {
	driver, ok := c.driver.(*sql.Driver)
	if !ok {
		return ErrInvalidDriver
	}

	return driver.DB().PingContext(ctx)
}
```
