### ISSUE TITLE
Public validation method?

### ISSUE THREAD

**Issue by sundowndev** [facebookincubator/ent#669]
I was looking for a way to validate my object before creating it in the database. I saw you use `preSave()` method to perform pre-save validation, is there a way to perform this validation by myself without saving?

example case:

```go
v, err := client.Video.
		Create().
		SetTitle(body.Title).
		Save(context.Background())
	if err != nil {
                // error...
		httputils.NewError(ctx, http.StatusBadRequest, err)
		return
	}

// success...
```

Problem: any kind of error would return an HTTP 400 here.

Possible solution:

```go
v, err := client.Video.
    Create().
    SetTitle(body.Title).
    Validate()
if err != nil {
    // validation errors
    httputils.NewError(ctx, http.StatusBadRequest, err)
    return
}

_, err := v.Save(context.Background())
if err != nil {
    // any other error
    httputils.NewError(ctx, http.StatusInternalServerError, err)
    return
}

// success
```

`entity.Validate()` could return either an error or an array of errors : `entity.Validate() []error`

Very nice project tho, great design, keep up the good job 👍

**Comment by a8m** [comment]
Hey @sundowndev and thanks for the feedback - it's great to hear that 😃 

There are a few ways to do it: 
- If you want to validate one or more fields, use the [fields validator option](https://entgo.io/docs/schema-fields/#validators) in the schema.
- You can use [hooks](https://entgo.io/docs/hooks/) - let me know if you need help with that (a new section with hook examples is going to be added to the docs next week). 
- If you still want your own `Validate` function, you can use [external templates](https://entgo.io/docs/templates/) to generate this logic.

Let me know if you need help with that.

**Comment by sundowndev** [comment]
Thank you @a8m , I ended up with this solution after seeing #547  :

```go
v, err := db.Client.Video.
		Create().
		SetTitle(body.Title).
		SetStatus(schema.VideoStatusProcessing).
		Save(context.Background())
	if ent.IsValidationError(err) {
		httputils.NewError(ctx, http.StatusBadRequest, err)
		return
	}
	if err != nil {
		httputils.NewError(ctx, http.StatusInternalServerError, err)
		return
	}
```

**Quick question:** If I want to override the default `ent:` prefix in errors I need to use custom template, right?

**Comment by a8m** [comment]
> Quick question: If I want to override the default ent: prefix in errors I need to use custom template, right?

No, you should able to use `errors.Unwrap(err)` to get this - I just fixed the error unwrapping for `ValidationError`, so if you update to latest version (master) you'll get this. 

See an [example](https://github.com/facebookincubator/ent/blob/6fe7023d6abaeaa5194939a0cbb4366b67fd0369/entc/integration/integration_test.go#L581-L583) in integration tests.

**Comment by a8m** [comment]
Closing, but you can feel free to continue the discussion or reopen if the issue wasn't resolved.
