### ISSUE TITLE
Postgres Extension

### ISSUE THREAD

**Issue by cliedeman** [facebookincubator/ent#69]
Hello,

I am interested in using this library with postgres. I took a stab at adding postgres but hit a wall with the builder. The mysql quote identifier (backtick) is hardcoded in the file. My first idea was to switch on the dialect but it is not available.

Examples:
* https://github.com/facebookincubator/ent/blob/master/dialect/sql/builder.go#L50
*m https://github.com/facebookincubator/ent/blob/master/dialect/sql/builder.go#L1215
* https://github.com/facebookincubator/ent/blob/master/dialect/sql/builder.go#L1241
* https://github.com/facebookincubator/ent/blob/master/dialect/sql/builder.go#L1381

Edit: ? for args is also an issue

Ciaran

**Comment by a8m** [comment]
There are some changes that need to be done before adding the PostgreSQL support. One of them, is to make the identifier quote character configurable. I can add this in the upcoming days, and you can take it from there if you want.

**Comment by cliedeman** [comment]
Thanks. It’s a bit of invasive change so it’s better if a maintainer makes it. But I think Postgres numbered arguments will be a bigger issue?

**Comment by cliedeman** [comment]
I created a PR with my WIP if anyone wants to check it out https://github.com/facebookincubator/ent/pull/78

**Comment by a8m** [comment]
PostgreSQL support was added. Thanks a lot for your contribution!

**Comment by frederikhors** [comment]
> PostgreSQL support was added. Thanks a lot for your contribution!

Any "read more" link about? Is it already in master?

**Comment by a8m** [comment]
It's on master. The usage is similar to other dialects - https://entgo.io/docs/crud
