### ISSUE TITLE
Any way to run raw SQL query?

### ISSUE THREAD

**Issue by leafduo** [facebookincubator/ent#85]
I like statically typed APIs, but sometimes we need to run raw SQLs to get functionalities of specific RDBMS. Currently, I don't find any way to do that.

**Comment by leafduo** [comment]
`dialect.Driver` or `sql.DB` are both OK, but that requires passing additional struct around since `ent.Client` doesn't provide a way to get underlying driver or db.

**Comment by a8m** [comment]
> ent.Client doesn't provide a way to get underlying driver or db.

Yeah, because we believe it's not required for most of the use cases, and we prefer to stick with the type-safe API. However, predicates can be customized.

Can you share your use case, or what is missing in the client? Thanks.

**Comment by a8m** [comment]
Hey, closing this issue since I don't think there's an action item here.

If you want to add custom methods to `*ent.Client` (or any other type), you can either use [external templates](https://entgo.io/docs/code-gen/#external-templates), or just add them manually to an `external.go` file under the `<project>/ent` directory. For example:

```go
func (c *Client) DB() *sql.DB {
  return c.driver.(*entsql.Driver).DB()
}
```

**Comment by ansarizafar** [comment]
It would be great If ent.Client exposes underlying driver or db by default so that we don't have to do it our self every time we generate the code. I want to execute following commands after client is connected to database.
```
set search_path to 'schema'
set timezone TO 'GMT';
```

**Comment by a8m** [comment]
> that we don't have to do it our self every time we generate the code. 

How do you run codegen? I'm trying to figure out why do you need to rewrite it after each codegen?

If you delete the `ent` directory before each codegen, I'll recommend you to use [templates](https://entgo.io/docs/code-gen/#external-templates). For example:
```go
{{ define "external" }}
package ent

func (c *Client) DB() *sql.DB {
  return c.driver.(*entsql.Driver).DB()
}
{{ end }}
```

**Comment by ansarizafar** [comment]
I mean every time we generate the code for a new project. The workaround is simple but its more convenient to expose DB() method as part of the client api by default specially for PostgreSQL.

**Comment by giautm** [comment]
Only one reason for me to access underly `*sql.DB` is creating `sqlhealth.Checker`. So, I write custom template that generates `health.Checker` for gocloud kit.

```
{{ define "sqlhealth" }}

{{ $pkg := base $.Config.Package }}
{{- with extend $ "Package" $pkg }}
        {{ template "header" . }}
{{- end }}

import (
	"entgo.io/ent/dialect/sql"
	"gocloud.dev/server/health/sqlhealth"
)

func (c *Client) HealthCheck() *sqlhealth.Checker {
	db := c.driver.(*sql.Driver).DB()
	return sqlhealth.New(db)
}
{{ end }}
```

```go
// appHealthChecks returns a health check for the database. This will signal
// to Kubernetes or other orchestrators that the server should not receive
// traffic until the server is able to connect to its database.
func appHealthChecks(ent *entv1.Client) ([]health.Checker, func()) {
	dbCheck := ent.HealthCheck()
	list := []health.Checker{dbCheck}
	return list, func() {
		dbCheck.Stop()
	}
}
```

**Comment by manakuro** [comment]
If you use debug mode by default and run into the error:

```
interface conversion: dialect.Driver is *dialect.DebugDriver, not *sql.Driver
```

Try this one.

```.go
func (c *Client) DB() *sql.DB {
	if c.debug {
            return c.driver.(*dialect.DebugDriver).Driver.(*entsql.Driver).DB()
	}
	return c.driver.(*entsql.Driver).DB()
}
```

**Comment by a8m** [comment]
Hey all! I added a feature flag named [sql/execquery](https://entgo.io/docs/feature-flags#sql-raw-api) to simplify the process for those who need it.

**Comment by a8m** [comment]
Hey @leafduo 👋 

Can you please update ent to the latest master and try again? `go get entgo.io/ent/cmd/ent@master`

**Comment by HackingGate** [comment]
> `//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/execquery ./ent/schema`

This worked for me.
